export interface ProductDetail {
  name: string;
  brand: string;
  segment: string;
  description: string;
  highlight: string;
  specs: { label: string; value: string }[];
  colors: string;
  features: string[];
}

/* ── INFISSI ALLUMINIO — Oknoplast ─────────────────────────────── */

export const aluminumDetails: Record<string, ProductDetail> = {
  "Titano": {
    name: "Titano",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Finestra in alluminio a taglio termico con fermavetro squadrato a 90° e tripla guarnizione di serie. Il vetro extra-chiaro basso-emissivo con gas argon e canalina Swisspacer garantisce prestazioni termiche ai vertici della categoria.",
    highlight: "Prestazioni titaniche — tripla guarnizione, Uw fino a 0,78",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico" },
      { label: "Guarnizioni", value: "3 di serie (elastomero termoplastico)" },
      { label: "Trasmittanza Uw", value: "fino a 0,78 W/m²K (con Swisspacer)" },
      { label: "Isolamento acustico", value: "elevato (tripla guarnizione)" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo, doppio o triplo, argon" },
    ],
    colors: "RAL standard, metallizzato, effetto legno, anodizzato, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas", "Fermavetro 90°"],
  },
  "Titano EVO": {
    name: "Titano EVO",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "Evoluzione del Titano con maniglia centrata e nodo centrale ridotto per simmetria perfetta e massima superficie vetrata. I profili snelli dell'anta ampliano la visuale e il vetro extra-chiaro aumenta la trasparenza.",
    highlight: "Maniglia centrata, nodo ridotto — simmetria e luce al massimo",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico evoluto" },
      { label: "Guarnizioni", value: "3 di serie (elastomero termoplastico)" },
      { label: "Trasmittanza Uw", value: "fino a 0,78 W/m²K (con Swisspacer)" },
      { label: "Isolamento acustico", value: "elevato (tripla guarnizione)" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo, doppio o triplo, argon" },
    ],
    colors: "RAL standard, metallizzato, effetto legno, anodizzato, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas", "Maniglia centrata"],
  },
  "Titano OC": {
    name: "Titano OC",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Versione OC (Anta a Scomparsa) del Titano: il telaio si incassa nella muratura, lasciando visibile dall'esterno solo la superficie vetrata. Profili ultra-sottili e tripla guarnizione in elastomero termoplastico per tenuta perfetta.",
    highlight: "Anta a scomparsa — dall'esterno solo vetro, Uw 0,77",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico, anta a scomparsa" },
      { label: "Guarnizioni", value: "3 in elastomero termoplastico a memoria di forma" },
      { label: "Trasmittanza Uw", value: "fino a 0,77 W/m²K (con Swisspacer)" },
      { label: "Isolamento acustico", value: "elevato (tripla guarnizione)" },
      { label: "Classe sicurezza", value: "fino a RC2 (con sensori anti-intrusione)" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo ad alta trasparenza, argon" },
    ],
    colors: "RAL standard, metallizzato, effetto legno, anodizzato, bicolore",
    features: ["Anta a scomparsa", "Battente", "Anta-ribalta", "Fermavetro 90°"],
  },
  "Titano EVO OC": {
    name: "Titano EVO OC",
    brand: "Oknoplast",
    segment: "Top di gamma",
    description:
      "Il top di gamma assoluto: unisce la maniglia centrata e il nodo ridotto del Titano EVO con l'anta a scomparsa della versione OC. Profilo perimetrale completamente nascosto nella muratura per simmetria e trasparenza in perfetta armonia.",
    highlight: "EVO + anta a scomparsa — il vertice dell'alluminio Oknoplast",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico evoluto, anta a scomparsa" },
      { label: "Guarnizioni", value: "3 in elastomero termoplastico a memoria di forma" },
      { label: "Trasmittanza Uw", value: "fino a 0,77 W/m²K (con Swisspacer)" },
      { label: "Isolamento acustico", value: "elevato (tripla guarnizione)" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo super trasparente, argon" },
    ],
    colors: "RAL standard, metallizzato, effetto legno, anodizzato, bicolore",
    features: ["Anta a scomparsa", "Maniglia centrata", "Nodo ridotto", "Fermavetro 90°"],
  },
  "Titano Steel": {
    name: "Titano Steel",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Stile industrial autentico: profili decorativi sagomati su telaio e anta richiamano le finestre in acciaio delle architetture industriali. Terza guarnizione di serie, testata contro raffiche fino a 160 km/h e oltre 12 ore di pioggia battente.",
    highlight: "Design industrial — testata a 160 km/h di vento, Uw 0,80",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico con profili sagomati" },
      { label: "Guarnizioni", value: "3 di serie (terza guarnizione centrale)" },
      { label: "Trasmittanza Uw", value: "fino a 0,80 W/m²K (con isolante termico)" },
      { label: "Resistenza al vento", value: "testata fino a 160 km/h" },
      { label: "Tenuta pioggia", value: "oltre 12 ore di pioggia battente" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Doppio o triplo vetro basso-emissivo" },
    ],
    colors: "RAL standard, metallizzato, effetto legno, anodizzato spazzolato/sabbiato",
    features: ["Battente", "Anta-ribalta", "Profili industrial", "Fermavetro 90°"],
  },
  "Futural": {
    name: "Futural",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Finestra in alluminio dalle linee squadrate e minimali con taglio termico e isolamento aggiuntivo. Le guarnizioni in elastomero termoplastico a memoria di forma garantiscono tenuta perfetta nel tempo. Vetro extra-chiaro basso-emissivo con gas argon.",
    highlight: "Design squadrato minimale — Uw fino a 0,96 con doppio vetro",
    specs: [
      { label: "Profondità profilo", value: "alluminio a taglio termico squadrato" },
      { label: "Guarnizioni", value: "in elastomero termoplastico a memoria di forma" },
      { label: "Trasmittanza Uw", value: "fino a 0,96 W/m²K" },
      { label: "Isolamento acustico", value: "elevato (struttura robusta)" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo, doppio o triplo, argon" },
    ],
    colors: "Oltre 2000 colori RAL, Decoral, Timeless, effetto legno, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas", "Portafinestra", "Fermavetro 90°"],
  },
  "Futural OC": {
    name: "Futural OC",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "La finestra invisibile: il telaio scompare completamente nella muratura, lasciando visibile solo il vetro. Nodo centrale di soli 77 mm di larghezza per un effetto tutto-vetro dall'esterno. Disponibile con doppio o triplo vetro.",
    highlight: "La finestra invisibile — nodo 77 mm, Uw fino a 1,2 con triplo vetro",
    specs: [
      { label: "Nodo centrale", value: "77 mm" },
      { label: "Guarnizioni", value: "in elastomero termoplastico a memoria di forma" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m²K (con triplo vetro)" },
      { label: "Isolamento acustico", value: "elevato (struttura robusta)" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Extra-chiaro basso-emissivo, doppio o triplo, argon" },
    ],
    colors: "Oltre 2000 colori RAL, Decoral, Timeless, effetto legno, bicolore",
    features: ["Anta a scomparsa", "Battente", "Anta-ribalta", "Effetto tutto-vetro"],
  },
  "Prolux ALU": {
    name: "Prolux ALU",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "La piattaforma Prolux sbarca nell'alluminio: profilo ultra-sottile senza fermavetro tradizionale, con vetro incollato direttamente al profilo per un effetto frameless. Tre guarnizioni di serie e riduzione acustica fino a 38 dB certificati.",
    highlight: "Vetro incollato frameless — 3 guarnizioni, 38 dB, Uw 1,00",
    specs: [
      { label: "Profondità profilo", value: "alluminio ultra-sottile, vetro incollato" },
      { label: "Guarnizioni", value: "3 di serie" },
      { label: "Trasmittanza Uw", value: "fino a 1,00 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 38 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Incollato al profilo, doppio o triplo, basso-emissivo" },
    ],
    colors: "Standard, Decoral, Timeless, effetto legno, RAL personalizzato",
    features: ["Vetro incollato (no fermavetro)", "Battente", "Anta-ribalta", "Anta nascosta"],
  },
};

/* ── PORTE INTERNE — Pail + Door Arreda ────────────────────────── */

export const interiorDoorDetails: Record<string, ProductDetail> = {
  /* ── PAIL ────────────────────────────────────────────────── */
  "Pail — Laccate": {
    name: "Porte Laccate",
    brand: "Pail",
    segment: "Design",
    description:
      "Superficie liscia e minimale disponibile in tutti i colori RAL, finiture opache o lucide, con vernici antigraffio a base d'acqua. Il modello Linea è il più versatile; disponibile anche con inserti vetro satinato o trasparente per illuminare gli ambienti.",
    highlight: "Superficie liscia RAL — antigraffio, anche con inserti vetro",
    specs: [
      { label: "Materiale", value: "Pannello laccato liscio" },
      { label: "Finitura", value: "Opaca o lucida, tutti i colori RAL" },
      { label: "Vernice", value: "Base acqua, antigraffio" },
      { label: "Telaio", value: "Era, Evo, Line SP, Mimetica (filomuro)" },
      { label: "Consegna", value: "Rapido Pail — 15 giorni lavorativi" },
      { label: "Produzione", value: "Made in Italy — 75.000 porte/anno" },
    ],
    colors: "Tutti i colori RAL, latte, ardesia, sabbia, canapa, gesso, londra",
    features: ["Battente", "Scorrevole interno muro", "Scorrevole esterno", "Filomuro Mimetica", "Vetro opzionale"],
  },
  "Pail — Pantografate": {
    name: "Porte Pantografate",
    brand: "Pail",
    segment: "Design",
    description:
      "10 collezioni con incisioni CNC che creano geometrie in rilievo sulla superficie laccata. Ogni collezione prende il nome da città e offre varianti con disegni unici: dalle linee intersecate (Riga) alle curve morbide (Luna), dal bassorilievo effetto cammeo (Cammeo) alle texture animalier.",
    highlight: "10 collezioni pantografate — geometrie in rilievo, 60+ varianti città",
    specs: [
      { label: "Materiale", value: "Pannello pantografato CNC laccato" },
      { label: "Collezioni", value: "Riga, Luna, Cammeo, Pegaso, Pianeta, Stella, Nova Stella, Onda, Globo, Animalier" },
      { label: "Varianti per collezione", value: "Da 4 a 14, ispirate a città (Roma, Milano, Londra, Parigi...)" },
      { label: "Telaio", value: "Era, Evo, Line SP, Mimetica (filomuro)" },
      { label: "Consegna", value: "Rapido Pail — 15 giorni lavorativi" },
      { label: "Produzione", value: "Made in Italy — 75.000 porte/anno" },
    ],
    colors: "Laccato latte, ardesia, sabbia, canapa, gesso, londra, tutti i colori RAL",
    features: ["Battente", "Scorrevole interno muro", "Filomuro Mimetica", "Doppia anta"],
  },
  "Pail — Essenze": {
    name: "Porte in Essenza",
    brand: "Pail",
    segment: "Design",
    description:
      "Porte in Tecnorovere con 11 finiture naturali (dal Bianco al Fumé) e 16+ laminati decorati antigraffio (serie Quercia 4D, Olmo, Rovere). Modelli base Linea, Marsia, Demetra, Reflex e Infinita con inserti metallici opzionali in cromo, ottone o inox.",
    highlight: "11 finiture Tecnorovere + 16 laminati — inserti metallici opzionali",
    specs: [
      { label: "Materiale", value: "Tecnorovere (essenza tecnica rovere) o laminato decorato" },
      { label: "Finiture Tecnorovere", value: "Bianco, Sabbia, Nocciola, Grigio, Tortora, Castagno, Tabacco, Cacao, Fumé, Naturale, Multinoce" },
      { label: "Laminati decorati", value: "Quercia 4D (Calderone, Maiella, Gran Sasso, Laga), Olmo, Rovere, Canaletto, Wenge" },
      { label: "Modelli", value: "Linea, Marsia, Demetra, Reflex, Infinita, Replay, Gaia, Geo, Intarsio" },
      { label: "Inserti", value: "Cromo satinato, cromo lucido, ottone, inox (opzionali)" },
      { label: "Produzione", value: "Made in Italy — 75.000 porte/anno" },
    ],
    colors: "11 Tecnorovere + Multinoce, 16+ laminati decorati, inserti cromo/ottone/inox",
    features: ["Battente", "Scorrevole interno muro", "Scorrevole esterno", "Filomuro"],
  },
  "Pail — Boiserie": {
    name: "Tratto Boiserie",
    brand: "Pail",
    segment: "Premium",
    description:
      "Reinterpretazione contemporanea della boiserie francese: un fitto disegno di linee verticali in rilievo dona movimento alla superficie. Il sistema boiserie integrato trasforma l'intera parete in un elemento d'arredo coordinato con l'anta.",
    highlight: "Porta + boiserie integrata — la parete diventa arredo coordinato",
    specs: [
      { label: "Materiale", value: "Tecnorovere (essenza tecnica)" },
      { label: "Struttura", value: "Porta + pannelli boiserie coordinati" },
      { label: "Finitura", value: "Tecnorovere Naturale, laccato RAL, varianti colore" },
      { label: "Telaio", value: "Line SP con boiserie integrata" },
      { label: "Maniglia", value: "AGB Wave cromo-satinato" },
      { label: "Produzione", value: "Made in Italy" },
    ],
    colors: "Tecnorovere Naturale, laccato RAL, finiture coordinate alla boiserie",
    features: ["Battente", "Scorrevole (Attraction)", "Filomuro", "Boiserie parete"],
  },
  "Pail — Dolcevita": {
    name: "Dolcevita",
    brand: "Pail",
    segment: "Premium",
    description:
      "Collezione premium con 4 sotto-linee: Incanto (inserti legno spazzolato + laccato, 8 varianti), Prima (design esclusivi come Kilt in tartan e Chic in pelle), Opera (ispirazione bugnato classico), Venezia (cornici da palazzo storico). Finiture artigianali d'eccellenza.",
    highlight: "4 linee premium — Incanto, Prima, Opera, Venezia. Artigianato d'eccellenza",
    specs: [
      { label: "Sotto-collezioni", value: "Incanto (8 var.), Prima (10 var.), Opera (4 var.), Venezia (3 var.)" },
      { label: "Incanto", value: "Inserti legno spazzolato alternati a laccato liscio — vetro opzionale" },
      { label: "Prima", value: "Kilt (tartan), Chic (pelle), One (Shiny specchio), Seven, Emme" },
      { label: "Venezia", value: "Cornici classiche multi-livello, ispirazione palazzo storico" },
      { label: "Spessore anta", value: "44 mm" },
      { label: "Produzione", value: "Made in Italy — collezione premium" },
    ],
    colors: "Laccato latte, avorio, bianco anticato, Shiny (Bordeaux, Grigio, Latte), patinato",
    features: ["Battente", "Scorrevole esterno", "Doppia anta", "Vetro opzionale"],
  },
  "Pail — Vetro": {
    name: "Belvedere & Vetro",
    brand: "Pail",
    segment: "Premium",
    description:
      "Porte panoramiche con ampie vetrate incorniciate in rovere verniciato a cera. Disponibili battente, scorrevole parallelo fino a 4 ante, interno muro e esterno muro. Vetri STOPSOL Bronze, satinato, trasparente o bronzo. Ideali per creare connessioni visive tra gli ambienti.",
    highlight: "Vetrate panoramiche in rovere — fino a 4 ante, vetro STOPSOL Bronze",
    specs: [
      { label: "Materiale", value: "Rovere verniciato a cera (Tecnorovere)" },
      { label: "Finitura", value: "Tecnorovere grigio, naturale, sabbia" },
      { label: "Vetro", value: "STOPSOL Bronze, trasparente, satinato, bronzo satinato, grigio" },
      { label: "Configurazioni", value: "Battente, parallelo 4 ante, scorrevole interno/esterno" },
      { label: "Sotto-linee", value: "Belvedere (panoramico), Versione Vetro (inserti), Panorama (full-glass)" },
      { label: "Produzione", value: "Made in Italy" },
    ],
    colors: "Tecnorovere grigio, naturale, sabbia — vetro STOPSOL/trasparente/satinato/bronzo",
    features: ["Battente", "Scorrevole parallelo 4 ante", "Scorrevole interno muro", "Scorrevole esterno"],
  },
  "Pail — Shiny": {
    name: "One Prima Shiny",
    brand: "Pail",
    segment: "Luxury",
    description:
      "Finitura ultra-brillante con effetto specchio della linea Dolcevita Prima. Trasforma la porta in un elemento di design d'impatto per interni luxury e showroom. Disponibile anche il sistema filomuro Mimetica per scomparsa totale nella parete, e i sistemi scorrevoli Magic Slide.",
    highlight: "Effetto specchio luxury — Bordeaux, Latte, Grigio Shiny",
    specs: [
      { label: "Finitura", value: "Ultra-brillante effetto specchio" },
      { label: "Colori Shiny", value: "Bordeaux, Latte, Grigio, RAL 3020" },
      { label: "Filomuro", value: "Mimetica 43, 43 SP, 28 Efficient — scompare nella parete" },
      { label: "Scorrevoli", value: "Magic Slide (scomparsa totale), esterno, interno muro" },
      { label: "Aperture speciali", value: "Piega (libro), Rotea, Nova Libra, Cabin Pull" },
      { label: "Produzione", value: "Made in Italy — collezione luxury" },
    ],
    colors: "Bordeaux Shiny, Latte Shiny, Grigio Shiny, RAL 3020 Shiny; filomuro stuccabile RAL",
    features: ["Battente", "Filomuro Mimetica", "Magic Slide", "Scorrevole esterno", "Piega (libro)"],
  },

  /* ── DOOR ARREDA ─────────────────────────────────────────── */
  "Door Arreda — Tineo": {
    name: "Tineo",
    brand: "Door Arreda",
    segment: "Design",
    description:
      "La collezione più ampia di Door Arreda: 28 modelli tamburati (TL00–TL07) in legno liscio, svetrato o inciso, con inserti alluminio opzionali. Innumerevoli finiture — rovere, cedro, frassino, olmo, acero, larice, laccato Sable, Resin, Arbol — tutto su misura senza sovrapprezzo.",
    highlight: "28 modelli tamburati su misura — personalizzazione totale senza sovrapprezzo",
    specs: [
      { label: "Modelli", value: "TL00, TL01, TL02, TL03, TL04 (vetro), TL06 (inserto alluminio), TL07" },
      { label: "Essenze", value: "Rovere, cedro bianco, frassino bianco/grigio, olmo sabbia/tortora, acero perla, larice antico" },
      { label: "Laccati Sable", value: "Antracite, Avio, Avorio, Bianco, Canapa, Cocoa, Corda, Nero, Salvia, RAL" },
      { label: "Altre finiture", value: "Texture, Arbol, Resin (Calce, Carbone, Nebula, Tabacco), Paint" },
      { label: "Dimensioni", value: "Largh. 68–88 cm, Alt. 214 cm (custom disponibile)" },
      { label: "Produzione", value: "100% Made in Italy — su misura senza costi aggiuntivi" },
    ],
    colors: "10+ essenze naturali, 10+ laccati Sable, 4 Resin, Texture, Arbol, RAL personalizzato",
    features: ["Battente a spingere/tirare", "Filo parete", "Scorrevole Ghost", "Piego 180°"],
  },
  "Door Arreda — Fila": {
    name: "Fila",
    brand: "Door Arreda",
    segment: "Design",
    description:
      "12 modelli tamburati (FL50–FL58, FL77) coordinati nel design con la collezione Seven in vetro, per coerenza estetica in tutta la casa. Finiture prevalentemente laccate Sable e Bianco DA, ideali per ambienti dove legno e vetro si alternano.",
    highlight: "12 modelli coordinati con Seven — coerenza legno/vetro in tutta la casa",
    specs: [
      { label: "Modelli", value: "FL50, FL51, FL52, FL53, FL54, FL55, FL56, FL57, FL58, FL77" },
      { label: "Coordinamento", value: "Design coordinato con Seven (porte in vetro)" },
      { label: "Finiture laccate", value: "Sable (Canapa, Avorio, Bianco, Corda, RAL), Bianco DA, Paint" },
      { label: "Telaio", value: "TOP, Trend, Trend S, Filo Parete, Coplan, Coplan-S" },
      { label: "Personalizzazione", value: "Su misura senza sovrapprezzo" },
      { label: "Produzione", value: "100% Made in Italy" },
    ],
    colors: "Laccato Sable (canapa, avorio, bianco, corda, RAL), Bianco DA, Paint",
    features: ["Battente a spingere/tirare", "Filo parete"],
  },
  "Door Arreda — Pandora": {
    name: "Pandora",
    brand: "Door Arreda",
    segment: "Design",
    description:
      "Due anime in una collezione: Pandora Design (6 modelli con incisioni geometriche a sbalzo — effetti scultorei di luce e ombra) e Pandora Classic (5 modelli con pannelli bugnati classici, compatibili con filo muro e pivot). Tutte su misura senza sovrapprezzo.",
    highlight: "Design + Classic — sculture di luce (Design) e bugne classiche (Classic) in un'unica linea",
    specs: [
      { label: "Pandora Design", value: "PC11, PC12, PC13, PC32, PC33 — incisioni geometriche a sbalzo" },
      { label: "Pandora Classic", value: "PC01, PC02, PC03, PC05, PC06 — pannelli bugnati classici" },
      { label: "Finiture Design", value: "Bianco DA, Sable canapa/avorio/cocoa/corda" },
      { label: "Finiture Classic", value: "Laccato bianco, avorio" },
      { label: "Aperture Classic", value: "Battente, filo muro, bilico (pivot)" },
      { label: "Produzione", value: "100% Made in Italy — su misura" },
    ],
    colors: "Bianco DA, Sable (canapa, avorio, cocoa, corda), laccato bianco/avorio, RAL",
    features: ["Battente", "Filo parete", "Bilico/pivot (Classic)"],
  },
  "Door Arreda — Seven": {
    name: "Seven",
    brand: "Door Arreda",
    segment: "Design",
    description:
      "21 modelli di porte in vetro con cornice alluminio, completamente su misura. 10 sotto-linee (Sendy, Shine, Shop, Simple, Star, Sun, Sonny, Sky, Six, Sintli) con 30+ motivi di vetro decorativo. Fino a 100×270 cm (battente) e 140×270 cm (scorrevole).",
    highlight: "21 modelli vetro + alluminio — 10 linee, 30+ vetri decorativi, tutto su misura",
    specs: [
      { label: "Sotto-linee", value: "Sendy, Shine, Shop (nero industrial), Simple, Star (pivot), Sun, Sonny, Sky, Six, Sintli" },
      { label: "Vetri standard", value: "Float (neutro, bronze, grey), Satin (bronze, grey, bianco, neutro)" },
      { label: "Vetri decorativi", value: "30+ motivi: Bubble, Casablanca, Dune, Ethno, Fire, Krepa, Lignes, Millerighe, Taffeta..." },
      { label: "Cornice", value: "Bianco, moka, nero, larice antico, laccato RAL" },
      { label: "Max dimensioni", value: "Battente: 100×270 cm — Scorrevole: 140×270 cm" },
      { label: "Produzione", value: "100% Made in Italy — su misura senza sovrapprezzo" },
    ],
    colors: "Alluminio bianco, moka, nero, larice antico, RAL — vetro bronze/grey/satin/taffeta/decorativo",
    features: ["Battente", "Scorrevole interna/esterna", "Filo parete", "Flag/bilico (pivot)"],
  },
  "Door Arreda — Meraki": {
    name: "Meraki",
    brand: "Door Arreda",
    segment: "Premium",
    description:
      "Collezione rivoluzionaria con un segno grafico unico che attraversa la superficie. Inserti in 5 materiali pregiati rendono ogni porta irriproducibile. Modelli Elysia (Metal, Wood) e Klissa (Metal, Stone, Wood) disponibili in laccato Sable, Bianco DA, Texture e Resin.",
    highlight: "Segno grafico unico — inserti in alluminio, oro, metallo nero, pietra o legno",
    specs: [
      { label: "Modelli", value: "Elysia Metal, Elysia Wood, Klissa Metal, Klissa Stone, Klissa Wood" },
      { label: "Inserti", value: "Alluminio, metallo nero opaco, oro satinato, pietra naturale, legno" },
      { label: "Finiture base", value: "Bianco DA, Sable (10+ colori), Texture Sable, Resin (4 varianti)" },
      { label: "Telaio", value: "TOP, Trend, Trend S, Filo Parete, Coplan, Coplan-S" },
      { label: "Dimensioni", value: "Largh. 68–88 cm, Alt. 214 cm (custom disponibile)" },
      { label: "Produzione", value: "100% Made in Italy — pezzo unico" },
    ],
    colors: "Bianco DA, Sable multi-colore, Texture Sable, Resin — inserto alluminio/nero/oro/pietra/legno",
    features: ["Battente (pivot)", "Cerniera nascosta", "Filo parete"],
  },
  "Door Arreda — Seven Minimo": {
    name: "Seven Minimo",
    brand: "Door Arreda",
    segment: "Premium",
    description:
      "Evoluzione della Seven: sistema integrato partizione vetrata + porta coordinata che si installa senza telai strutturali. Fino a 1500×3000 mm. Porte Shine con telaio oro spazzolato e partizioni SKY con vetro Flutes. Anche in versione pivot (flag/bilico).",
    highlight: "Partizione + porta integrata — fino a 3 m, senza telaio strutturale, anche pivot",
    specs: [
      { label: "Sistema", value: "Partizione vetrata integrata con porta coordinata" },
      { label: "Modelli porta", value: "Shine (battente/bilico), SKY (partizione + pivot)" },
      { label: "Max dimensioni", value: "1500×3000 mm" },
      { label: "Vetro", value: "Flutes (vert./oriz.), Float bronze, Taffeta (bianco/grigio/marrone/nero)" },
      { label: "Cornice", value: "Nero, oro spazzolato, bianco" },
      { label: "Produzione", value: "100% Made in Italy" },
    ],
    colors: "Cornice nero, oro spazzolato, bianco — vetro Flutes/bronze/Taffeta",
    features: ["Battente", "Flag/bilico (pivot)", "Partizione vetrata fissa"],
  },
  "Door Arreda — Green": {
    name: "Green",
    brand: "Door Arreda",
    segment: "Design",
    description:
      "Reinterpretazione moderna di modelli classici in due stili: Incise (incisioni geometriche in cedro del Libano per un effetto raffinato) e Scolpite (lavorazione scultorea classica rivisitata in chiave contemporanea). Anche la Luce completa la gamma con un design essenziale a soli montanti laterali.",
    highlight: "Incise + Scolpite — cedro del Libano, tradizione artigianale contemporanea",
    specs: [
      { label: "Green Incise", value: "GI45 — incisioni geometriche in cedro del Libano" },
      { label: "Green Scolpite", value: "GS43 — lavorazione scultorea classica rivisitata" },
      { label: "Luce", value: "LV20 — solo montanti laterali, vetro satinato bronzo/grigio" },
      { label: "Dimensioni Green", value: "Alt. 2100/2400 mm, Largh. 600–800 mm" },
      { label: "Finiture", value: "Arbol Bianco DA, Avio Sable, laccato palette completa" },
      { label: "Produzione", value: "100% Made in Italy" },
    ],
    colors: "Arbol Bianco DA, Avio Sable, larice antico, grigio spazzolato",
    features: ["Battente", "Filo parete", "Scorrevole esterna (Luce)"],
  },
};

/* ── PORTE BLINDATE — Alias + Erreci ──────────────────────────── */

export const securityDoorDetails: Record<string, ProductDetail> = {
  "Alias — Wall": {
    name: "Wall",
    brand: "Alias",
    segment: "Premium",
    description:
      "L'unica vera porta blindata completamente rasomuro: complanare alla parete interna, senza coprifili ne cornici visibili. Certificata Classe RC3 secondo EN 1627 con isolamento termico Ud 1,0 W/m²K e acustico fino a 45 dB. Disponibile anche nella versione antincendio EI2-60.",
    highlight: "L'unica blindata rasomuro vera — RC3, Ud 1,0, fino a 45 dB",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 (EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,0 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB (con kit acustico)" },
      { label: "Resistenza fuoco", value: "EI2-60 opzionale (EN 1634-1)" },
      { label: "Serratura", value: "Cilindro europeo, motorizzata opzionale" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Pannello grezzo con primer (stuccabile/tinteggiabile), laccato RAL, effetto legno",
    features: ["Rasomuro interno (ed esterno con Kit E-Wall)", "Pannello personalizzabile", "Maniglia MANU design Ivo Pellegri", "Versione antincendio EI2-60"],
  },
  "Alias — Twenty LED": {
    name: "Twenty",
    brand: "Alias",
    segment: "Design",
    description:
      "Porta blindata sensoriale che arricchisce la Wing Wall con linee luminose LED integrate nei profili laterali. L'illuminazione a LED crea un effetto cornice che dona vita agli ambienti anche al buio. Stesse prestazioni RC3 della Wall.",
    highlight: "LED perimetrale integrato — cornice luminosa, blindata RC3",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 (EN 1627)" },
      { label: "Illuminazione", value: "LED integrato nei profili laterali" },
      { label: "Trasmittanza Ud", value: "1,0 W/m²K (come Wall)" },
      { label: "Isolamento acustico", value: "fino a 45 dB (con kit acustico)" },
      { label: "Serratura", value: "Cilindro europeo, motorizzata opzionale" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Pannello grezzo con primer (tinteggiabile), laccato RAL, personalizzabile",
    features: ["Filomuro interno", "LED integrato nei profili", "Maniglia Wall cromo satinato", "Pannello personalizzabile"],
  },
  "Alias — Dream": {
    name: "Dream",
    brand: "Alias",
    segment: "Design",
    description:
      "Porta blindata per interni firmata Alias: isolamento acustico Rw 33 dB di serie (il doppio di una porta interna tradizionale), classe RC2. Pensata per studi, camere e ambienti privati dove serve sicurezza senza compromessi estetici.",
    highlight: "Blindata per interni — RC2, Rw 33 dB (doppio di una porta normale)",
    specs: [
      { label: "Classe antieffrazione", value: "RC2" },
      { label: "Isolamento acustico", value: "Rw 33 dB di serie" },
      { label: "Set acustico", value: "Di serie" },
      { label: "Serratura", value: "Cilindro europeo di sicurezza" },
      { label: "Coordinabilità", value: "Abbinabile alle porte interne esistenti" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Laccato, essenza, pannelli decorativi, coordinabile con porte interne",
    features: ["Per interni (studi, camere, uffici)", "Pannelli intercambiabili", "Filomuro opzionale"],
  },
  "Alias — Dream One": {
    name: "Dream One",
    brand: "Alias",
    segment: "Premium",
    description:
      "Evoluzione del Dream con telaio in alluminio anodizzato rinforzato da struttura in ferro zincato. Classe RC3, isolamento acustico Rw 40 dB e trasmittanza Ud 1,2 W/m²K. Versatile e adattiva, si coordina con le porte interne gia presenti in casa.",
    highlight: "RC3, Rw 40 dB, Ud 1,2 — telaio alluminio anodizzato rinforzato",
    specs: [
      { label: "Classe antieffrazione", value: "RC3" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "Rw 40 dB" },
      { label: "Tenuta aria", value: "Classe 2" },
      { label: "Resistenza vento", value: "C2" },
      { label: "Telaio", value: "Alluminio anodizzato + ferro zincato" },
    ],
    colors: "Coprifilo laccato RAL (7032, 7044, 9010), collezioni (DE)SIGN e RENO",
    features: ["Telaio alluminio anodizzato", "Maniglia H4/Fenix", "Collezione (DE)SIGN", "Collezione RENO", "Coordinabile con porte interne"],
  },
  "Alias — Due Ante": {
    name: "Due Ante (Double)",
    brand: "Alias",
    segment: "Premium",
    description:
      "Porta blindata a doppia anta con cerniera nascosta, sinonimo di grandiosità e maestosità. Certificata Classe 3 con trasmittanza Ud 1,29 W/m²K e riduzione acustica 36 dB. Apertura singola o doppia per ingressi scenografici di ville e attici.",
    highlight: "Doppia anta Classe 3 — Ud 1,29, 36 dB, cerniera nascosta",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 3 (cerniera nascosta, EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,29 W/m²K" },
      { label: "Isolamento acustico", value: "36 dB" },
      { label: "Serratura", value: "Doppia serratura cilindro europeo" },
      { label: "Pannello", value: "Collezione Diamante (es. A111), 6-15 mm" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Collezione Diamante, pannelli legno, laccato, effetto pietra, RAL",
    features: ["Due ante blindate", "Cerniera nascosta", "Apertura singola o doppia", "Maniglia H4 cromo satinato"],
  },
  "Alias — Magma": {
    name: "Magma",
    brand: "Alias",
    segment: "Sicurezza",
    description:
      "Porta tagliafuoco blindata disponibile in tre versioni: Magma 30, 60 e 90 minuti di resistenza al fuoco (EI2-30/60/90 secondo EN 1634-1). Serratura motorizzata con possibilità di maniglione antipanico. Dimensioni standard e fuori misura disponibili.",
    highlight: "Tagliafuoco EI2 30-60-90 min — serratura motorizzata, antipanico",
    specs: [
      { label: "Resistenza fuoco", value: "EI2-30, EI2-60, EI2-90 (EN 1634-1)" },
      { label: "Trasmittanza Ud", value: "Magma 30: 2,00 / Magma 60: 1,60 / Magma 90: 2,00 W/m²K" },
      { label: "Isolamento acustico", value: "Magma 30: 42 dB / Magma 60: 40 dB / Magma 90: 42 dB" },
      { label: "Serratura", value: "Motorizzata, con/senza maniglione antipanico" },
      { label: "Dimensioni std", value: "L 80/85/90 cm × H 210 cm" },
      { label: "Dimensioni max", value: "L 80-103 cm × H 190-230 cm (max 2,16 m²)" },
    ],
    colors: "Pannelli personalizzabili a scelta",
    features: ["Tagliafuoco EI2 certificata", "Serratura motorizzata", "Maniglione antipanico opzionale", "Misure standard e fuori misura"],
  },
  "Alias — Steel": {
    name: "Steel",
    brand: "Alias",
    segment: "Entry",
    description:
      "Porta blindata con cerniere a vista in Classe RC3, pannello esterno laccato liscio RAL 7044 e maniglia H4 cromo satinato. Dotata di cilindro anti-bumping, sistema anti-trapano e anti-sfilamento, tre guarnizioni e sistema light-stop. Ideale come primo ingresso sicuro senza rinunciare all'estetica.",
    highlight: "RC3, cerniere a vista — anti-bumping, 3 guarnizioni, light-stop",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 (EN 1627)" },
      { label: "Pannello esterno", value: "Laccato liscio RAL 7044" },
      { label: "Cilindro", value: "Anti-bumping di serie" },
      { label: "Guarnizioni", value: "3 di serie" },
      { label: "Protezioni", value: "Anti-trapano, anti-sfilamento, light-stop" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "RAL 7044 standard, laminati Black Matrix, pannelli personalizzabili",
    features: ["Cerniere a vista regolabili", "Anti-bumping di serie", "Light-stop integrato", "Pannello personalizzabile"],
  },
  "Alias — Silver": {
    name: "Silver",
    brand: "Alias",
    segment: "Design",
    description:
      "Porta blindata con cerniera nascosta in Classe RC3 per un'estetica pulita e lineare. Trasmittanza Ud 1,30 W/m²K e isolamento acustico 34 dB. Sistema anti-trapano, anti-sfilamento, cilindro anti-bumping e tre guarnizioni di serie. La scelta ideale per chi desidera sicurezza senza cerniere visibili.",
    highlight: "RC3, cerniera nascosta — Ud 1,30, 34 dB, estetica pulita",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 (EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,30 W/m²K" },
      { label: "Isolamento acustico", value: "34 dB" },
      { label: "Cerniere", value: "Nascoste" },
      { label: "Guarnizioni", value: "3 di serie + light-stop" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Laccato RAL, laminato, essenza legno, pannelli personalizzabili",
    features: ["Cerniera nascosta", "Anti-trapano e anti-sfilamento", "Cilindro anti-bumping", "Light-stop integrato"],
  },
  "Alias — Gold": {
    name: "Gold",
    brand: "Alias",
    segment: "Premium",
    description:
      "Evoluzione della Silver con doppi deviatori per una sicurezza rinforzata. Stesse prestazioni RC3 con cerniera nascosta, Ud 1,30 W/m²K e 34 dB di isolamento acustico. I doppi deviatori aumentano i punti di chiusura rendendo la porta ancora più resistente alle effrazioni.",
    highlight: "RC3 + doppi deviatori — cerniera nascosta, sicurezza rinforzata",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 (EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,30 W/m²K" },
      { label: "Isolamento acustico", value: "34 dB" },
      { label: "Deviatori", value: "Doppi (sicurezza rinforzata)" },
      { label: "Cerniere", value: "Nascoste" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Laccato RAL, laminato, essenza legno, pannelli personalizzabili",
    features: ["Doppi deviatori", "Cerniera nascosta", "Sicurezza rinforzata", "Pannello personalizzabile"],
  },
  "Alias — Platinum": {
    name: "Platinum",
    brand: "Alias",
    segment: "Massima Sicurezza",
    description:
      "Porta blindata di massima sicurezza in Classe RC4 con cerniera nascosta. Trasmittanza Ud 1,45 W/m²K e isolamento acustico 35 dB. La struttura rinforzata e il cilindro certificato Classe 4 la rendono la scelta per chi non accetta compromessi sulla protezione della propria abitazione.",
    highlight: "RC4, cerniera nascosta — massima classe di sicurezza residenziale",
    specs: [
      { label: "Classe antieffrazione", value: "RC4 (EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,45 W/m²K" },
      { label: "Isolamento acustico", value: "35 dB" },
      { label: "Cilindro", value: "Certificato Classe 4 (Tipo A o Tipo S)" },
      { label: "Cerniere", value: "Nascoste" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Laccato RAL, laminato, essenza legno, pannelli decorativi a scelta",
    features: ["Classe RC4", "Cerniera nascosta", "Cilindro certificato Classe 4", "Struttura rinforzata"],
  },
  "Alias — Slalom": {
    name: "Slalom",
    brand: "Alias",
    segment: "Innovazione",
    description:
      "Porta blindata a bilico roto-traslante con due brevetti europei. Apertura scenografica con luce netta superiore rispetto alle porte tradizionali. Ud 1,2 W/m²K, Rw 40 dB, resistenza al vento C2. Dimensioni ottimali 1200×3000 mm, massimo 1500×4000 mm. Maniglie esclusive di Ivo Pellegri nelle finiture Champagne, Copper, Gun Metal e Cromo Satinato.",
    highlight: "Porta a bilico — 2 brevetti europei, apertura scenografica, Rw 40 dB",
    specs: [
      { label: "Tipo apertura", value: "Bilico roto-traslante (2 brevetti EU)" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "Rw 40 dB" },
      { label: "Resistenza vento", value: "C2" },
      { label: "Dimensioni ottimali", value: "1200 × 3000 mm" },
      { label: "Dimensioni max", value: "1500 × 4000 mm" },
    ],
    colors: "Maniglie: Champagne, Copper, Gun Metal, Cromo Satinato. Pannelli personalizzabili",
    features: ["Bilico roto-traslante brevettato", "Luce netta superiore", "Maniglie Ivo Pellegri", "Filomuro o tradizionale interno"],
  },
  "Alias — Flat": {
    name: "Flat",
    brand: "Alias",
    segment: "Design",
    description:
      "Porta blindata coplanare: telaio e profili scompaiono, lasciando una superficie completamente piatta e continua con la parete. Disponibile sulle strutture Silver, Gold, Platinum e Titanium. L'estetica minimale più estrema applicata alla sicurezza.",
    highlight: "Coplanare — telaio invisibile, superficie continua con la parete",
    specs: [
      { label: "Tipo", value: "Coplanare (frame-less)" },
      { label: "Strutture disponibili", value: "Silver (RC3), Gold (RC3), Platinum (RC4), Titanium (RC4)" },
      { label: "Pannello", value: "Complanare alla parete — superficie piatta" },
      { label: "Variante", value: "Flat e Flat Infinity" },
      { label: "Cerniere", value: "Nascoste" },
      { label: "Garanzia", value: "30 anni di durabilità testata" },
    ],
    colors: "Laccato RAL, laminato, essenza legno, personalizzabile",
    features: ["Telaio e profili invisibili", "Superficie complanare", "Da RC3 a RC4", "Variante Flat Infinity"],
  },
  "Alias — Vega Plus": {
    name: "Vega Plus",
    brand: "Alias",
    segment: "Sicurezza",
    description:
      "Porta blindata con cerniere a vista disponibile in Classe RC3 e RC4. Rinforzo centrale a doppia omega, piastre in acciaio da 3 mm sui punti di cerniere e serrature, tripli deviatori inclinati. Trasmittanza Ud 1,45 W/m²K (riducibile a 0,3 in meno con opzione aerogel) e 35 dB di isolamento acustico.",
    highlight: "RC3/RC4, doppia omega — tripli deviatori inclinati, opzione aerogel",
    specs: [
      { label: "Classe antieffrazione", value: "RC3 / RC4 (EN 1627)" },
      { label: "Trasmittanza Ud", value: "1,45 W/m²K (fino a 1,15 con aerogel)" },
      { label: "Isolamento acustico", value: "35 dB" },
      { label: "Rinforzo", value: "Doppia omega centrale + piastre 3 mm" },
      { label: "Deviatori", value: "Tripli inclinati" },
      { label: "Cilindro", value: "Certificato Classe 4 (Tipo A o S)" },
    ],
    colors: "Pannelli personalizzabili, collezioni outdoor e indoor",
    features: ["Doppia omega + piastre 3 mm", "Tripli deviatori inclinati", "Opzione isolamento aerogel", "Cerniere a vista regolabili"],
  },
  "Erreci — Capri": {
    name: "Capri",
    brand: "Erreci",
    segment: "Sicurezza",
    description:
      "Porta blindata Classe 3 con lamiera esterna in acciaio zincato 12/10 e doppia nervatura omega di rinforzo. Isolamento termoacustico in EPS grafitato su entrambi i lati. 15 punti di chiusura totali con deviatore a tripla chiusura superiore/inferiore.",
    highlight: "Classe 3, Ud 1,2, 40 dB — 15 punti di chiusura, EPS grafitato",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 3" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Tenuta aria", value: "Classe 3" },
      { label: "Resistenza vento", value: "Classe 5c" },
      { label: "Punti chiusura", value: "15 totali (cerniere 3 assi + perni fissi + deviatore)" },
      { label: "Lamiera esterna", value: "Acciaio zincato monolamina 12/10 + doppia omega" },
      { label: "Controtelaio", value: "Acciaio zincato saldato 20/10" },
    ],
    colors: "Essenze pannello personalizzabili, telaio RAL 9010/9005/8019/7035, bicolore",
    features: ["15 punti di chiusura", "Deviatore tripla chiusura", "EPS grafitato", "Cerniere regolabili 3 assi", "6 perni fissi anti-scardinamento"],
  },
  "Erreci — Capri Serrature": {
    name: "Capri — Opzioni Serratura",
    brand: "Erreci",
    segment: "Sicurezza",
    description:
      "La porta blindata Capri offre un ampio ventaglio di serrature: dalla classica a cilindro singolo/doppio alle versioni motorizzate con transponder, tastiera digitale, biometria o riconoscimento combinato. Dimensioni standard 80-90×210 cm, su misura fino a 110×245 cm.",
    highlight: "7 tipi di serratura — da cilindro classico a biometrica Full",
    specs: [
      { label: "Serratura Normal", value: "Cilindro singolo/doppio con defender" },
      { label: "Serratura Simply", value: "Motorizzata con transponder" },
      { label: "Serratura Digit", value: "Motorizzata con tastiera numerica" },
      { label: "Serratura Bio", value: "Motorizzata biometrica (impronta)" },
      { label: "Serratura Full", value: "Motorizzata con riconoscimento combinato" },
      { label: "Dimensioni standard", value: "L 800/850/900 mm × H 2100 mm" },
      { label: "Dimensioni su misura", value: "L 700-1100 mm × H 1800-2450 mm" },
    ],
    colors: "Maniglie bronzo o alluminio argento, combinazioni pomolo/maniglia",
    features: ["Cilindro europeo con defender", "Serratura motorizzata", "Transponder", "Tastiera digitale", "Lettore biometrico", "Drop 20 barriera termica a pavimento"],
  },
  "Erreci — Ischia": {
    name: "Ischia",
    brand: "Erreci",
    segment: "Massima Sicurezza",
    description:
      "Porta blindata Classe 4 con 17 punti di chiusura e doppi rinforzi strutturali. Lamiera in acciaio zincato 12/10 con doppia omega e traversi orizzontali, isolamento in EPS grafitato. Prestazioni termoacustiche eccellenti: Ud 1,2 W/m²K e 40 dB. Disponibile con serrature motorizzate fino alla versione biometrica Full.",
    highlight: "Classe 4, 17 punti chiusura — doppi rinforzi, Ud 1,2, 40 dB",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 4 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "17 totali" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Tenuta aria", value: "Classe 3" },
      { label: "Resistenza vento", value: "Classe 5c" },
      { label: "Lamiera", value: "Acciaio zincato 12/10 + doppia omega + traversi" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato, bicolore",
    features: ["17 punti di chiusura", "Doppia omega + traversi orizzontali", "EPS grafitato", "3 cerniere regolabili 3 assi", "Serrature fino a motorizzata Full"],
  },
  "Erreci — Lampedusa": {
    name: "Lampedusa",
    brand: "Erreci",
    segment: "Massima Sicurezza",
    description:
      "La massima sicurezza nel catalogo Erreci: Classe 5 con rivestimento esterno in lamiera di acciaio al manganese resistente a taglio e trapanazione. 17 punti di chiusura, cilindro Top Secur Widia protetto da taglio e strappo, deviatori a gancio. Ud 1,2 W/m²K e 40 dB di isolamento acustico. Spessore anta 65 mm.",
    highlight: "Classe 5 — acciaio al manganese, cilindro Top Secur Widia, max protezione",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 5 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "17 totali" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Spessore anta", value: "65 mm" },
      { label: "Lamiera esterna", value: "Acciaio al manganese anti-taglio" },
      { label: "Cilindro", value: "Top Secur Widia (anti-taglio, anti-strappo)" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato, bicolore",
    features: ["Classe 5 massima sicurezza", "Acciaio al manganese", "Cilindro Top Secur Widia", "Deviatori a gancio", "Serrature fino a motorizzata Bio/Full"],
  },
  "Erreci — Maddalena": {
    name: "Maddalena",
    brand: "Erreci",
    segment: "Design",
    description:
      "Porta blindata Classe 3 con cerniere nascoste SIMONSWERK e apertura coplanare a 180°. 11 punti di chiusura, Ud 1,2 W/m²K e 40 dB. Disponibile a singola o doppia anta con sopraluce e pannelli laterali. L'eleganza della cerniera nascosta con la sicurezza Erreci.",
    highlight: "Classe 3, cerniere SIMONSWERK — apertura coplanare 180°",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 3 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "11 totali" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Tenuta aria", value: "Classe 3" },
      { label: "Resistenza vento", value: "Classe 5c" },
      { label: "Tenuta acqua", value: "Classe 2a" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato, bicolore",
    features: ["Cerniere nascoste SIMONSWERK", "Apertura coplanare 180°", "Singola o doppia anta", "Sopraluce e pannelli laterali", "EPS grafitato"],
  },
  "Erreci — Panarea": {
    name: "Panarea",
    brand: "Erreci",
    segment: "Design",
    description:
      "Porta blindata Classe 3 con cerniere nascoste e linee essenziali per un'integrazione perfetta nella parete. 11 punti di chiusura, Ud 1,2 W/m²K e 40 dB di abbattimento acustico. Design raffinato che rispetta elevati standard di sicurezza. Compatibile con serrature Simply e motorizzate.",
    highlight: "Classe 3, cerniere nascoste — design essenziale, 40 dB",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 3 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "11 totali" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Tenuta aria", value: "Classe 3" },
      { label: "Resistenza vento", value: "Classe 4c" },
      { label: "Cerniere", value: "2 nascoste regolabili 3 assi + 4 perni fissi" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato, bicolore",
    features: ["Cerniere nascoste", "Design essenziale e lineare", "Serratura Simply transponder", "Serratura motorizzata opzionale", "EPS grafitato"],
  },
  "Erreci — Pianosa": {
    name: "Pianosa",
    brand: "Erreci",
    segment: "Design",
    description:
      "Porta blindata filomuro Classe 3: nessun telaio, coprifilo o modanatura visibile. Si integra perfettamente nella parete come un elemento d'arredo invisibile. Cerniere nascoste con apertura a 95°, 11 punti di chiusura, Ud 1,2 W/m²K e 40 dB. Discrezione assoluta.",
    highlight: "Filomuro Classe 3 — senza coprifili, integrazione totale nella parete",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 3 (UNI-EN 1627)" },
      { label: "Tipo", value: "Filomuro (senza coprifili visibili)" },
      { label: "Punti chiusura", value: "11 totali" },
      { label: "Trasmittanza Ud", value: "1,2 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Tenuta acqua", value: "Classe 2a" },
      { label: "Cerniere", value: "2 nascoste, apertura 95°, regolabili 3 assi" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato, bicolore",
    features: ["Filomuro senza coprifili", "Integrazione totale nella parete", "Cerniere nascoste 95°", "Serratura motorizzata opzionale", "EPS grafitato"],
  },
  "Erreci — Marettimo": {
    name: "Marettimo",
    brand: "Erreci",
    segment: "Smart / Innovazione",
    description:
      "Porta blindata smart Classe 4 senza maniglia con retroilluminazione LED programmabile e controllo via app Bluetooth. 17 punti di chiusura, Ud 1,3 W/m²K e 40 dB. La centralina elettronica gestisce apertura automatica, illuminazione e inserimento catenacci. Serratura esclusivamente motorizzata Bio o Full con biometria.",
    highlight: "Classe 4 smart — LED, app Bluetooth, senza maniglia, biometrica",
    specs: [
      { label: "Classe antieffrazione", value: "Classe 4 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "17 totali" },
      { label: "Trasmittanza Ud", value: "1,3 W/m²K" },
      { label: "Isolamento acustico", value: "40 dB" },
      { label: "Smart", value: "Centralina elettronica, Bluetooth, app dedicata" },
      { label: "Illuminazione", value: "LED retroilluminato programmabile" },
      { label: "Serrature", value: "Motorizzata Bio (impronta) o Full (biometrica)" },
    ],
    colors: "RAL 9010, 9005, 8019, 7035, RAL personalizzato",
    features: ["Senza maniglia", "LED retroilluminato programmabile", "Controllo via app Bluetooth", "Serratura biometrica", "Cerniere nascoste", "Inserimento catenacci automatico"],
  },
  "Erreci — Vulcano": {
    name: "Vulcano Masterfire 90",
    brand: "Erreci",
    segment: "Tagliafuoco",
    description:
      "Porta blindata tagliafuoco certificata REI 90: resiste 90 minuti a fiamme e fumi. Classe 3 antieffrazione con 11 punti di chiusura. Lamiera in acciaio zincato 15/10 (più spessa degli altri modelli), chiudiporta pneumatico e guarnizioni termoespandenti. Certificata sia in apertura a spinta che a tiro.",
    highlight: "REI 90 + Classe 3 — tagliafuoco 90 min, lamiera 15/10",
    specs: [
      { label: "Resistenza fuoco", value: "REI 90 (90 minuti)" },
      { label: "Classe antieffrazione", value: "Classe 3 (UNI-EN 1627)" },
      { label: "Punti chiusura", value: "11 totali" },
      { label: "Isolamento acustico", value: "28 dB" },
      { label: "Trasmittanza Ud", value: "1,8 W/m²K" },
      { label: "Lamiera", value: "Acciaio zincato 15/10 (rinforzata)" },
      { label: "Cerniere", value: "3 in ferro regolabili 3 assi + 5 perni fissi" },
    ],
    colors: "Telaio RAL 9005 standard, pannelli personalizzabili",
    features: ["REI 90 certificata", "Chiudiporta pneumatico", "Guarnizioni termoespandenti", "Apertura a spinta e a tiro", "Maniglione antipanico opzionale"],
  },
};
