export interface WindowDetail {
  name: string;
  segment: string;
  description: string;
  highlight: string;
  profileDepth: string;
  chambers: string;
  thermalUw: string;
  acousticDb: string;
  security: string;
  glassType: string;
  colors: string;
  openingTypes: string[];
}

export const windowDetails: Record<string, WindowDetail> = {
  "Prolux": {
    name: "Prolux",
    segment: "Classic",
    description: "La finestra iconica Oknoplast con profilo brevettato a 6 camere e design classico arrotondato. Il vetro extra-chiaro e il nodo centrale ridotto garantiscono fino al 22% di luce naturale in più rispetto a una finestra PVC tradizionale.",
    highlight: "Il best-seller Oknoplast — +22% di luce naturale",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 1,0 W/m²K",
    acousticDb: "fino a 39 dB",
    security: "fino a RC1",
    glassType: "Doppio vetro (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prolux Evolution": {
    name: "Prolux Evolution",
    segment: "Comfort",
    description: "L'evoluzione del Prolux con nodo centrale di soli 112 mm e maniglia posizionata esattamente al centro per una simmetria perfetta. Le guarnizioni in elastomero termoplastico a memoria di forma assicurano una tenuta duratura nel tempo.",
    highlight: "Simmetria perfetta con maniglia centrata e +22% di luce",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 0,8 W/m²K",
    acousticDb: "fino a 45 dB",
    security: "fino a RC2",
    glassType: "Doppio vetro (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Scorrevole Prolux": {
    name: "Scorrevole Prolux",
    segment: "Scorrevoli",
    description: "Sistema alzante-scorrevole HST Motion per aperture panoramiche oltre i 6 metri. Il profilo squadrato con vetro extra-chiaro garantisce massima luminosità, mentre la ferramenta dedicata assicura uno scorrimento fluido e senza sforzo.",
    highlight: "Aperture panoramiche oltre 6 metri con Uw 0,77",
    profileDepth: "82 mm",
    chambers: "6",
    thermalUw: "fino a 0,77 W/m²K",
    acousticDb: "elevato isolamento",
    security: "fino a RC2",
    glassType: "Doppio vetro (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Alzante-scorrevole HST"],
  },
  "Scorrevole Prolux Plus": {
    name: "Scorrevole Prolux Plus",
    segment: "Scorrevoli",
    description: "Il sistema scorrevole HST Premium con profilo da 85 mm e soglia ultra-ribassata di soli 2,5 cm per accessibilità senza barriere. L'anta fissa di soli 32 mm visibili minimizza l'ingombro per un effetto parete di vetro.",
    highlight: "Soglia 2,5 cm — accessibilità totale senza barriere",
    profileDepth: "85 mm",
    chambers: "5",
    thermalUw: "fino a 0,8 W/m²K",
    acousticDb: "elevato isolamento",
    security: "fino a RC2",
    glassType: "Triplo vetro",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Alzante-scorrevole HST"],
  },
  "Prolux Swing": {
    name: "Prolux Swing",
    segment: "Design",
    description: "Finestra basculante unica nel suo genere: l'anta si apre verso l'esterno ruotando fino a 170°, senza occupare spazio interno. Superfici vetrate fino a 2,45 m² e blocco di sicurezza bambini a 15°. Eletto Prodotto dell'Anno 2019.",
    highlight: "Prodotto dell'Anno 2019 — zero ingombro interno",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 0,9 W/m²K",
    acousticDb: "fino a 45 dB",
    security: "blocco sicurezza bambini a 15°",
    glassType: "Doppio vetro (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Basculante a 170°"],
  },
  "Prolux Vitro": {
    name: "Prolux Vitro",
    segment: "Premium",
    description: "La finestra a tutto vetro senza fermavetro visibili: il profilo scompare alla vista creando una superficie vetrata continua e senza interruzioni. Triplo vetro di serie con prestazioni da casa passiva.",
    highlight: "Effetto tutto-vetro con Uw 0,7 — standard passivo",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 0,7 W/m²K",
    acousticDb: "elevato isolamento",
    security: "fino a RC2",
    glassType: "Triplo vetro di serie",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta"],
  },
  "Platinium Plus": {
    name: "Platinium Plus",
    segment: "Comfort",
    description: "Profilo dalle proporzioni equilibrate con superficie vetrata ampliata e rinforzi in acciaio appositamente progettati per finestre di grande formato. Disponibile con opzione alucover per rivestimento esterno in alluminio.",
    highlight: "Grande formato con opzione alucover in alluminio",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 1,0 W/m²K",
    acousticDb: "fino a 39 dB",
    security: "fino a RC2",
    glassType: "Doppio vetro basso-emissivo (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Squareline": {
    name: "Squareline",
    segment: "Design",
    description: "Design brevettato con angoli perfettamente squadrati a 90° che enfatizzano la linea slim e minimale. Guarnizioni in elastomero termoplastico a memoria di forma coordinate al colore del profilo e vetro extra-chiaro per massima luminosità.",
    highlight: "Profilo brevettato con angoli a 90° perfetti",
    profileDepth: "70 mm",
    chambers: "6",
    thermalUw: "fino a 0,8 W/m²K",
    acousticDb: "fino a 45 dB",
    security: "fino a RC2",
    glassType: "Doppio vetro (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prismatic": {
    name: "Prismatic",
    segment: "Comfort",
    description: "Il profilo più compatto ad alte prestazioni della gamma Oknoplast. Grazie a 3 guarnizioni (anziché 2) e alla capacità di ospitare vetri fino a 48 mm di spessore, raggiunge un isolamento eccezionale in soli 76 mm di profondità.",
    highlight: "Il più compatto profilo ultra-isolante sul mercato",
    profileDepth: "76 mm",
    chambers: "5 + terza guarnizione centrale",
    thermalUw: "fino a 0,78 W/m²K",
    acousticDb: "fino a 45 dB",
    security: "fino a RC2",
    glassType: "Vetri fino a 48 mm (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prismatic Evolution": {
    name: "Prismatic Evolution",
    segment: "Premium",
    description: "Tutte le prestazioni isolanti del Prismatic con simmetria perfetta: nodo centrale ridotto e maniglia al centro esatto dell'anta. +22% di luce naturale rispetto a una finestra standard. Prodotto dell'Anno 2023.",
    highlight: "Prodotto dell'Anno 2023 — simmetria perfetta e Uw 0,78",
    profileDepth: "76 mm",
    chambers: "5 + terza guarnizione centrale",
    thermalUw: "fino a 0,78 W/m²K",
    acousticDb: "fino a 45 dB",
    security: "fino a RC2",
    glassType: "Vetri fino a 48 mm (triplo opzionale)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Premium": {
    name: "Winergetic Premium",
    segment: "Top di gamma",
    description: "L'ammiraglia Oknoplast: profilo brevettato a 7 camere con 82 mm, triplo vetro di serie e vetri leggeri da 3 mm che riducono il peso del 30%. Certificato CasaClima Classe A. Le linee squadrate con fermavetro a 90° donano un aspetto moderno e pulito.",
    highlight: "CasaClima Classe A — triplo vetro di serie, -30% peso",
    profileDepth: "82 mm",
    chambers: "7",
    thermalUw: "fino a 0,7 W/m²K",
    acousticDb: "fino a 47 dB",
    security: "fino a RC2",
    glassType: "Triplo vetro di serie (vetri leggeri 3 mm)",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Premium Passive": {
    name: "Winergetic Premium Passive",
    segment: "Passive House",
    description: "La prima finestra in PVC con tecnologia aerogel aerospaziale. Il sistema brevettato Space Block (aerogel + poliuretano) raggiunge il massimo isolamento mai ottenuto da una finestra Oknoplast. Certificato CasaClima Gold. Compatibile con telaio termico WARMATEC per un ulteriore -10% di dispersione.",
    highlight: "CasaClima Gold — tecnologia aerogel, Uw 0,6",
    profileDepth: "82 mm",
    chambers: "7",
    thermalUw: "fino a 0,6 W/m²K",
    acousticDb: "fino a 47 dB",
    security: "fino a RC2",
    glassType: "Quadruplo vetro extra-chiaro di serie",
    colors: "Bianco, pellicolati legno e colori RAL",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Alu": {
    name: "Winergetic Alu",
    segment: "Top di gamma",
    description: "L'ibrido PVC-alluminio che unisce le 7 camere del Winergetic Premium a un guscio esterno in alluminio. Personalizzazione illimitata con oltre 2000 colori RAL sull'esterno, mantenendo tutti i vantaggi termici del PVC all'interno. Telaio termico incluso per -10% di dispersione.",
    highlight: "7 camere PVC + guscio alluminio — 2000+ colori RAL",
    profileDepth: "82 mm",
    chambers: "7",
    thermalUw: "fino a 0,64 W/m²K",
    acousticDb: "fino a 47 dB",
    security: "fino a RC2",
    glassType: "Triplo vetro di serie",
    colors: "Oltre 2000 colori RAL sull'alluminio esterno",
    openingTypes: ["Battente", "Anta-ribalta", "Vasistas"],
  },
};
