import type { ProductDetail } from "./product-details";

/** Legacy alias kept for backward compatibility */
export type WindowDetail = ProductDetail;

export const windowDetails: Record<string, ProductDetail> = {
  "Prolux": {
    name: "Prolux",
    brand: "Oknoplast",
    segment: "Classic",
    description: "La finestra iconica Oknoplast con profilo brevettato a 6 camere e design classico arrotondato. Il vetro extra-chiaro e il nodo centrale ridotto garantiscono fino al 22% di luce naturale in più rispetto a una finestra PVC tradizionale.",
    highlight: "Il best-seller Oknoplast — +22% di luce naturale",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 1,0 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 39 dB" },
      { label: "Classe sicurezza", value: "fino a RC1" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prolux Evolution": {
    name: "Prolux Evolution",
    brand: "Oknoplast",
    segment: "Comfort",
    description: "L'evoluzione del Prolux con nodo centrale di soli 112 mm e maniglia posizionata esattamente al centro per una simmetria perfetta. Le guarnizioni in elastomero termoplastico a memoria di forma assicurano una tenuta duratura nel tempo.",
    highlight: "Simmetria perfetta con maniglia centrata e +22% di luce",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,8 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Scorrevole Prolux": {
    name: "Scorrevole Prolux",
    brand: "Oknoplast",
    segment: "Scorrevoli",
    description: "Sistema alzante-scorrevole HST Motion per aperture panoramiche oltre i 6 metri. Il profilo squadrato con vetro extra-chiaro garantisce massima luminosità, mentre la ferramenta dedicata assicura uno scorrimento fluido e senza sforzo.",
    highlight: "Aperture panoramiche oltre 6 metri con Uw 0,77",
    specs: [
      { label: "Profondità profilo", value: "82 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,77 W/m²K" },
      { label: "Isolamento acustico", value: "elevato isolamento" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Alzante-scorrevole HST"],
  },
  "Scorrevole Prolux Plus": {
    name: "Scorrevole Prolux Plus",
    brand: "Oknoplast",
    segment: "Scorrevoli",
    description: "Il sistema scorrevole HST Premium con profilo da 85 mm e soglia ultra-ribassata di soli 2,5 cm per accessibilità senza barriere. L'anta fissa di soli 32 mm visibili minimizza l'ingombro per un effetto parete di vetro.",
    highlight: "Soglia 2,5 cm — accessibilità totale senza barriere",
    specs: [
      { label: "Profondità profilo", value: "85 mm" },
      { label: "Camere", value: "5" },
      { label: "Trasmittanza Uw", value: "fino a 0,8 W/m²K" },
      { label: "Isolamento acustico", value: "elevato isolamento" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Triplo vetro" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Alzante-scorrevole HST"],
  },
  "Prolux Swing": {
    name: "Prolux Swing",
    brand: "Oknoplast",
    segment: "Design",
    description: "Finestra basculante unica nel suo genere: l'anta si apre verso l'esterno ruotando fino a 170°, senza occupare spazio interno. Superfici vetrate fino a 2,45 m² e blocco di sicurezza bambini a 15°. Eletto Prodotto dell'Anno 2019.",
    highlight: "Prodotto dell'Anno 2019 — zero ingombro interno",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,9 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "blocco sicurezza bambini a 15°" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Basculante a 170°"],
  },
  "Prolux Vitro": {
    name: "Prolux Vitro",
    brand: "Oknoplast",
    segment: "Premium",
    description: "La finestra a tutto vetro senza fermavetro visibili: il profilo scompare alla vista creando una superficie vetrata continua e senza interruzioni. Triplo vetro di serie con prestazioni da casa passiva.",
    highlight: "Effetto tutto-vetro con Uw 0,7 — standard passivo",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,7 W/m²K" },
      { label: "Isolamento acustico", value: "elevato isolamento" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Triplo vetro di serie" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta"],
  },
  "Platinium Plus": {
    name: "Platinium Plus",
    brand: "Oknoplast",
    segment: "Comfort",
    description: "Profilo dalle proporzioni equilibrate con superficie vetrata ampliata e rinforzi in acciaio appositamente progettati per finestre di grande formato. Disponibile con opzione alucover per rivestimento esterno in alluminio.",
    highlight: "Grande formato con opzione alucover in alluminio",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 1,0 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 39 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Doppio vetro basso-emissivo (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Squareline": {
    name: "Squareline",
    brand: "Oknoplast",
    segment: "Design",
    description: "Design brevettato con angoli perfettamente squadrati a 90° che enfatizzano la linea slim e minimale. Guarnizioni in elastomero termoplastico a memoria di forma coordinate al colore del profilo e vetro extra-chiaro per massima luminosità.",
    highlight: "Profilo brevettato con angoli a 90° perfetti",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,8 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prismatic": {
    name: "Prismatic",
    brand: "Oknoplast",
    segment: "Comfort",
    description: "Il profilo più compatto ad alte prestazioni della gamma Oknoplast. Grazie a 3 guarnizioni (anziché 2) e alla capacità di ospitare vetri fino a 48 mm di spessore, raggiunge un isolamento eccezionale in soli 76 mm di profondità.",
    highlight: "Il più compatto profilo ultra-isolante sul mercato",
    specs: [
      { label: "Profondità profilo", value: "76 mm" },
      { label: "Camere", value: "5 + terza guarnizione centrale" },
      { label: "Trasmittanza Uw", value: "fino a 0,78 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Vetri fino a 48 mm (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prismatic Evolution": {
    name: "Prismatic Evolution",
    brand: "Oknoplast",
    segment: "Premium",
    description: "Tutte le prestazioni isolanti del Prismatic con simmetria perfetta: nodo centrale ridotto e maniglia al centro esatto dell'anta. +22% di luce naturale rispetto a una finestra standard. Prodotto dell'Anno 2023.",
    highlight: "Prodotto dell'Anno 2023 — simmetria perfetta e Uw 0,78",
    specs: [
      { label: "Profondità profilo", value: "76 mm" },
      { label: "Camere", value: "5 + terza guarnizione centrale" },
      { label: "Trasmittanza Uw", value: "fino a 0,78 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Vetri fino a 48 mm (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Premium": {
    name: "Winergetic Premium",
    brand: "Oknoplast",
    segment: "Top di gamma",
    description: "L'ammiraglia Oknoplast: profilo brevettato a 7 camere con 82 mm, triplo vetro di serie e vetri leggeri da 3 mm che riducono il peso del 30%. Certificato CasaClima Classe A. Le linee squadrate con fermavetro a 90° donano un aspetto moderno e pulito.",
    highlight: "CasaClima Classe A — triplo vetro di serie, -30% peso",
    specs: [
      { label: "Profondità profilo", value: "82 mm" },
      { label: "Camere", value: "7" },
      { label: "Trasmittanza Uw", value: "fino a 0,7 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 47 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Triplo vetro di serie (vetri leggeri 3 mm)" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Premium Passive": {
    name: "Winergetic Premium Passive",
    brand: "Oknoplast",
    segment: "Passive House",
    description: "La prima finestra in PVC con tecnologia aerogel aerospaziale. Il sistema brevettato Space Block (aerogel + poliuretano) raggiunge il massimo isolamento mai ottenuto da una finestra Oknoplast. Certificato CasaClima Gold. Compatibile con telaio termico WARMATEC per un ulteriore -10% di dispersione.",
    highlight: "CasaClima Gold — tecnologia aerogel, Uw 0,6",
    specs: [
      { label: "Profondità profilo", value: "82 mm" },
      { label: "Camere", value: "7" },
      { label: "Trasmittanza Uw", value: "fino a 0,6 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 47 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Quadruplo vetro extra-chiaro di serie" },
    ],
    colors: "Bianco, pellicolati legno e colori RAL",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Winergetic Alu": {
    name: "Winergetic Alu",
    brand: "Oknoplast",
    segment: "Top di gamma",
    description: "L'ibrido PVC-alluminio che unisce le 7 camere del Winergetic Premium a un guscio esterno in alluminio. Personalizzazione illimitata con oltre 2000 colori RAL sull'esterno, mantenendo tutti i vantaggi termici del PVC all'interno. Telaio termico incluso per -10% di dispersione.",
    highlight: "7 camere PVC + guscio alluminio — 2000+ colori RAL",
    specs: [
      { label: "Profondità profilo", value: "82 mm" },
      { label: "Camere", value: "7" },
      { label: "Trasmittanza Uw", value: "fino a 0,64 W/m²K" },
      { label: "Isolamento acustico", value: "fino a 47 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Triplo vetro di serie" },
    ],
    colors: "Oltre 2000 colori RAL sull'alluminio esterno",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },

  /* ── Nuovi modelli Oknoplast 2024-2026 ────── */

  "Prolux Plus": {
    name: "Prolux Plus",
    brand: "Oknoplast",
    segment: "Premium",
    description: "Profilo asimmetrico da 76 mm con maniglia decentrata e vetro incollato (bonded glass): il fermavetro scompare alla vista creando una superficie liscia e continua dall'esterno. Tre guarnizioni di tenuta e classe RC1/RC2 opzionale.",
    highlight: "Vetro incollato senza fermavetro — profilo 76 mm, Uw 0,7",
    specs: [
      { label: "Profondità profilo", value: "76 mm" },
      { label: "Camere", value: "5 + guarnizione centrale" },
      { label: "Trasmittanza Uw", value: "fino a 0,7 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "fino a 38 dB" },
      { label: "Classe sicurezza", value: "RC1 / RC2 opzionale" },
      { label: "Vetro", value: "Triplo vetro incollato (bonded glass)" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL, Soft opaco, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Prolux Pi\u00F9": {
    name: "Prolux Pi\u00F9",
    brand: "Oknoplast",
    segment: "Premium",
    description: "La finestra pi\u00F9 innovativa della gamma Prolux: profilo simmetrico da 76 mm con maniglia centrata e nessun fermavetro visibile. Superfici pulite e massima superficie vetrata. Tre guarnizioni in elastomeri termoplastici. Prodotto dell'Anno 2026.",
    highlight: "Prodotto dell'Anno 2026 — zero fermavetro, Uw 0,7",
    specs: [
      { label: "Profondità profilo", value: "76 mm" },
      { label: "Camere", value: "5 + guarnizione centrale" },
      { label: "Trasmittanza Uw", value: "fino a 0,7 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "fino a 38 dB" },
      { label: "Classe sicurezza", value: "RC1 / RC2 opzionale" },
      { label: "Vetro", value: "Triplo vetro senza fermavetro" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL, Soft opaco, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas"],
  },
  "Koncept Plus": {
    name: "Koncept Plus",
    brand: "Oknoplast",
    segment: "Classic",
    description: "Finestra solida e versatile con profilo da 70 mm, triplo vetro extra-chiaro e guarnizioni a memoria di forma. Disponibile in forme speciali (circolari, triangolari, trapezoidali) e con cerniere invisibili e soglia ribassata Win Step opzionali.",
    highlight: "Forme speciali e cerniere invisibili — versatilità totale",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,92 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "fino a 45 dB" },
      { label: "Classe sicurezza", value: "RC1 / RC2 opzionale" },
      { label: "Vetro", value: "Triplo vetro extra-chiaro" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL, bicolore",
    features: ["Battente", "Anta-ribalta", "Vasistas", "Forme speciali"],
  },
  "Finestra a Bilico": {
    name: "Finestra a Bilico",
    brand: "Oknoplast",
    segment: "Design",
    description: "Finestra a bilico con apertura a 45° verso l'interno e rotazione completa a 180° per la pulizia del vetro esterno senza sforzo. Guarnizioni in elastomero termoplastico a memoria di forma. Disponibile anche in versione trapezoidale per mansarde.",
    highlight: "Bilico 45° + rotazione 180° per pulizia facile",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 0,9 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "elevato isolamento" },
      { label: "Classe sicurezza", value: "standard" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL",
    features: ["Bilico 45°", "Rotazione 180°", "Versione trapezoidale mansarda"],
  },
  "Prolux Slide": {
    name: "Prolux Slide",
    brand: "Oknoplast",
    segment: "Scorrevoli",
    description: "Sistema scorrevole complanare con profilo slim e soglia ribassata. Chiusura a pressione per una tenuta ottimale all'aria e all'acqua. Vetro extra-chiaro e design minimale per massima luminosit\u00E0.",
    highlight: "Scorrevole slim con soglia ribassata e chiusura a pressione",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 1,0 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "elevato isolamento" },
      { label: "Classe energetica", value: "A / A+" },
      { label: "Vetro", value: "Doppio vetro (triplo opzionale)" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL",
    features: ["Scorrevole complanare"],
  },
  "Traslante PSK": {
    name: "Traslante PSK",
    brand: "Oknoplast",
    segment: "Scorrevoli",
    description: "Sistema scorrevole a traslazione (PSK) con apertura anta-ribalta e scorrevole. Profilo da 82 mm con isolamento acustico fino a 47 dB. Classe RC2 opzionale per massima sicurezza. Certificabile CasaClima Gold.",
    highlight: "Traslante anta-ribalta + scorrevole — fino a 47 dB e RC2",
    specs: [
      { label: "Profondità profilo", value: "82 mm" },
      { label: "Camere", value: "7" },
      { label: "Trasmittanza Uw", value: "fino a 0,8 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "fino a 47 dB" },
      { label: "Classe sicurezza", value: "fino a RC2" },
      { label: "Vetro", value: "Triplo vetro extra-chiaro" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL",
    features: ["Traslante PSK", "Anta-ribalta + scorrevole"],
  },
  "Ekosol": {
    name: "Ekosol",
    brand: "Oknoplast",
    segment: "Scorrevoli",
    description: "Lo scorrevole pratico e salvaspazio: configurabile con 1 o 2 ante scorrevoli e maniglia a scomparsa opzionale. Guarnizioni a memoria di forma e vetro extra-chiaro per un ingresso di luce ottimale.",
    highlight: "Scorrevole pratico — 1 o 2 ante, maniglia a scomparsa",
    specs: [
      { label: "Profondità profilo", value: "70 mm" },
      { label: "Camere", value: "6" },
      { label: "Trasmittanza Uw", value: "fino a 1,4 W/m\u00B2K" },
      { label: "Isolamento acustico", value: "buon isolamento" },
      { label: "Classe energetica", value: "A" },
      { label: "Vetro", value: "Doppio vetro extra-chiaro" },
    ],
    colors: "Bianco, pellicolati legno, colori RAL",
    features: ["Scorrevole 1 o 2 ante"],
  },
};
