import type { ProductDetail } from "../product-details";

/* ── PORTONCINI — Oknoplast Tenvis / Kopen KDS 100 ──────────── */

export const portoncinoDetails: Record<string, ProductDetail> = {
  "Oknoplast — Tenvis Design Pro": {
    name: "Tenvis Design Pro",
    brand: "Oknoplast",
    segment: "Top di gamma",
    description:
      "Portoncino in alluminio dal design ultra-moderno: la maniglia tradizionale è sostituita da un'elegante gola incassata nel pannello con retroilluminazione LED opzionale. Pannelli in alluminio con riempimento in polistirene estruso XPS per isolamento termico e resistenza al fuoco eccezionali.",
    highlight: "Maniglia a gola integrata con LED — design purista, Ud 0,84",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
      { label: "Smart Home", value: "Smartphone, telecomando, lettore impronte" },
    ],
    colors: "RAL standard, metallizzato, Renolit/Decoral effetto legno, Timeless, bicolore",
    features: ["Maniglia a gola integrata retroilluminabile LED", "Pannello XPS resistente al fuoco", "Chiusura automatica 3 punti", "Smart Home compatibile"],
  },
  "Oknoplast — Tenvis Black Design": {
    name: "Tenvis Black Design",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Portoncini in alluminio con inserti decorativi in nero anodizzato che creano un contrasto magnetico con le finiture effetto legno o le tonalità chiare del pannello. Il nero enfatizza le linee geometriche, donando all'ingresso un fascino contemporaneo e deciso.",
    highlight: "Inserti black anodizzati su alluminio — contrasto magnetico",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Inserti", value: "Nero anodizzato" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
      { label: "Modelli", value: "12 varianti (Black 1 – Black 12)" },
    ],
    colors: "Effetto legno (rovere, noce, mogano), grigi RAL, bicolore — oltre 30 finiture",
    features: ["Decorazioni nero anodizzato", "Effetto legno naturale", "Chiusura automatica 3 punti", "Configuratore online Tenvis"],
  },
  "Oknoplast — Tenvis Intarsio": {
    name: "Tenvis Intarsio",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "Portoncini in alluminio con eleganti intarsi in acciaio inox e inserti in vetro che generano affascinanti giochi di luce. Ogni modello è pensato per catturare lo sguardo con un design di alto livello che unisce artigianalità e tecnologia.",
    highlight: "Intarsi in acciaio inox e vetro — giochi di luce unici",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Vetrocamera", value: "50 o 64 mm" },
      { label: "Decorazioni", value: "Acciaio inox" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
    ],
    colors: "RAL opachi, metallizzati, effetto legno, Corten, Concrete, bicolore",
    features: ["Intarsi in acciaio inox", "Inserti vetrocamera", "Chiusura automatica 3 punti", "Smart Home compatibile"],
  },
  "Oknoplast — Tenvis ECO": {
    name: "Tenvis ECO",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino in alluminio dal design sobrio e minimale, pensato per chi cerca prestazioni elevate a un prezzo accessibile. L'estetica pulita ed essenziale si adatta a qualsiasi contesto architettonico, senza rinunciare ai vantaggi della linea Tenvis.",
    highlight: "Qualità Tenvis al miglior prezzo — design essenziale, Ud 0,84",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
      { label: "Modelli", value: "15+ varianti" },
    ],
    colors: "RAL 9016, grigi, Renolit/Decoral, Timeless, bicolore",
    features: ["Design minimale essenziale", "Modelli con o senza vetro", "Chiusura automatica 3 punti", "Rapporto qualità-prezzo ottimale"],
  },
  "Oknoplast — Tenvis Infinity": {
    name: "Tenvis Infinity",
    brand: "Oknoplast",
    segment: "Top di gamma",
    description:
      "Portoncino in alluminio dal design ultra-contemporaneo con grandi pannelli vetrati a tutta altezza che massimizzano l'ingresso della luce naturale. L'effetto è un aspetto frameless e trasparente che dissolve il confine tra interno ed esterno, mantenendo isolamento e sicurezza ai vertici della gamma Tenvis.",
    highlight: "Vetrate full-height frameless — massima luminosità, triplo vetro 64 mm",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Vetrocamera", value: "fino a 64 mm triplo vetro" },
      { label: "Profilo", value: "75 mm" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
    ],
    colors: "RAL standard, metallizzato, Renolit/Decoral effetto legno, Timeless, bicolore",
    features: ["Pannelli vetrati a tutta altezza", "Aspetto frameless ultra-contemporaneo", "Triplo vetro fino a 64 mm", "Chiusura automatica 3 punti"],
  },
  "Oknoplast — Tenvis Groove": {
    name: "Tenvis Groove",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Portoncino in alluminio caratterizzato da scanalature orizzontali fresate CNC sul pannello, che creano un motivo contemporaneo dal forte impatto architettonico. Disponibile con o senza inserti in vetro, il Groove conferisce all'ingresso un ritmo visivo distintivo e deciso.",
    highlight: "Scanalature orizzontali CNC — pattern architettonico bold",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Lavorazione", value: "Fresatura CNC orizzontale" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
    ],
    colors: "RAL standard, metallizzato, Renolit/Decoral effetto legno, Timeless, bicolore",
    features: ["Scanalature orizzontali fresate CNC", "Disponibile con o senza vetro", "Look architettonico contemporaneo", "Chiusura automatica 3 punti"],
  },
  "Oknoplast — Tenvis Classic": {
    name: "Tenvis Classic",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino in alluminio dal gusto tradizionale con elementi decorativi classici come lesene, rosoni e bugne che richiamano l'architettura d'epoca. Ideale per abitazioni di stile classico e contesti storici, il Tenvis Classic offre un'ampia gamma di modelli dal fascino senza tempo con le prestazioni moderne della linea Tenvis.",
    highlight: "Estetica classica senza tempo — lesene, rosoni e bugne decorative",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
      { label: "Modelli", value: "Ampia gamma di modelli classici" },
    ],
    colors: "RAL standard, metallizzato, Renolit/Decoral effetto legno, bicolore",
    features: ["Elementi decorativi classici (lesene, rosoni, bugne)", "Adatto ad architetture d'epoca e tradizionali", "Ampia scelta di modelli", "Chiusura automatica 3 punti"],
  },
  "Oknoplast — Tenvis Inox": {
    name: "Tenvis Inox",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "Portoncino in alluminio impreziosito da inserti decorativi in acciaio inossidabile — barre, maniglie e motivi geometrici — che donano un aspetto moderno-elegante di grande raffinatezza. Le molteplici configurazioni degli inserti inox permettono di personalizzare l'ingresso con uno stile unico e ricercato.",
    highlight: "Inserti decorativi in acciaio inox — eleganza moderna e personalizzabile",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Decorazioni", value: "Acciaio inox (barre, geometrie, maniglie)" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
    ],
    colors: "RAL standard, metallizzato, Renolit/Decoral effetto legno, Timeless, bicolore",
    features: ["Inserti decorativi in acciaio inossidabile", "Molteplici configurazioni inox", "Look moderno-elegante", "Chiusura automatica 3 punti"],
  },
  "Oknoplast — Tenvis Vintage": {
    name: "Tenvis Vintage",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Portoncino in alluminio ispirato alle tradizionali porte in legno, con finiture effetto legno invecchiato e rustico che evocano il fascino nostalgico dell'artigianato di un tempo. Realizzato in moderno alluminio a taglio termico, unisce l'estetica calda e vissuta del legno alle prestazioni superiori in termini di durabilità, isolamento e sicurezza.",
    highlight: "Estetica legno invecchiato su alluminio — charme vintage, prestazioni moderne",
    specs: [
      { label: "Sistema", value: "Tenvis — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "fino a 0,84 W/m²K" },
      { label: "Pannello", value: "61 o 76 mm con XPS" },
      { label: "Profilo", value: "75 mm" },
      { label: "Finiture", value: "Effetto legno invecchiato / rustico" },
      { label: "Sicurezza", value: "Blocco automatico 3 punti + rosetta anti-scasso" },
    ],
    colors: "Finiture effetto legno invecchiato, rovere antico, noce rustico, bicolore",
    features: ["Finiture effetto legno invecchiato e rustico", "Charme nostalgico su alluminio moderno", "Durabilità superiore al legno naturale", "Chiusura automatica 3 punti"],
  },
  "Kopen — Vitrum": {
    name: "Vitrum",
    brand: "Kopen",
    segment: "Design",
    description:
      "Portoncino di design in cui il vetro diventa protagonista assoluto. Le ampie superfici vetrate conferiscono luminosità e raffinatezza, mentre il sistema KDS 100 in alluminio a taglio termico garantisce isolamento e sicurezza ai massimi livelli.",
    highlight: "Il vetro come protagonista assoluto — luminosità, KDS 100",
    specs: [
      { label: "Sistema", value: "KDS 100 — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "da 0,75 a 0,90 W/m²K" },
      { label: "Telaio", value: "84 mm" },
      { label: "Anta", value: "98 / 102 / 121 mm" },
      { label: "Classe antieffrazione", value: "RC2, RC3 o RC4 certificata" },
      { label: "Produzione", value: "100% Made in Italy, su misura" },
    ],
    colors: "70 colori standard, bicolore, rivestimenti in alluminio, legno, cemento o ceramica",
    features: ["Ampie superfici vetrate", "Serratura meccanica, automatica o biometrica", "Fino a RC4", "Su misura"],
  },
  "Kopen — Materika": {
    name: "Materika",
    brand: "Kopen",
    segment: "Top di gamma",
    description:
      "Portoncino esclusivo in cui materiali tradizionali e innovativi si fondono: rivestimenti in cemento, ceramica, pietra o metallo si integrano con la struttura in alluminio KDS 100. Ogni esemplare è unico e realizzato su misura.",
    highlight: "Materia come icona di stile — cemento, ceramica, pietra su alluminio",
    specs: [
      { label: "Sistema", value: "KDS 100 — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "da 0,75 a 0,90 W/m²K" },
      { label: "Telaio", value: "84 mm" },
      { label: "Classe antieffrazione", value: "RC2, RC3 o RC4 certificata" },
      { label: "Rivestimenti", value: "Cemento, ceramica, pietra, metallo, legno" },
      { label: "Produzione", value: "100% Made in Italy, su misura" },
    ],
    colors: "70 colori standard, bicolore, materiali speciali (cemento, ceramica, pietra, Corten)",
    features: ["Rivestimenti in materiali pregiati", "Serratura biometrica opzionale", "Formato XL fino a 2.800 mm", "Su misura"],
  },
  "Kopen — Pure": {
    name: "Pure",
    brand: "Kopen",
    segment: "Design",
    description:
      "Portoncino dal carattere minimale ed elegante, in cui la ricerca del dettaglio costruttivo si traduce in superfici pulite e linee essenziali. La struttura KDS 100 è completamente nascosta, lasciando in primo piano la purezza del pannello.",
    highlight: "Purezza minimale — linee essenziali, dettaglio perfetto",
    specs: [
      { label: "Sistema", value: "KDS 100 — alluminio a taglio termico" },
      { label: "Trasmittanza Ud", value: "da 0,75 a 0,90 W/m²K" },
      { label: "Telaio", value: "84 mm" },
      { label: "Anta", value: "98 / 102 / 121 mm" },
      { label: "Classe antieffrazione", value: "RC2, RC3 o RC4 certificata" },
      { label: "Produzione", value: "100% Made in Italy, su misura" },
    ],
    colors: "70 colori standard, bicolore, finiture opache e metallizzate, legno interno",
    features: ["Design minimale", "Serratura biometrica opzionale", "Fino a RC4", "Su misura"],
  },

  /* ── Portoncini PVC Oknoplast ───────────────────────────── */

  "Oknoplast — Napoli": {
    name: "Napoli",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino d'ingresso in PVC dal design classico con pannello liscio e vetrocamera decorativa. Profilo a 5 camere da 70 mm per un buon isolamento termico, chiusura multipoint e soglia ribassata per un accesso comodo e sicuro.",
    highlight: "Ingresso classico in PVC — profilo 70 mm, 5 camere, vetrocamera 24 mm",
    specs: [
      { label: "Materiale", value: "PVC a 5 camere" },
      { label: "Profilo", value: "70 mm" },
      { label: "Pannello", value: "24 mm" },
      { label: "Vetrocamera", value: "24 mm doppio vetro" },
      { label: "Trasmittanza Uw", value: "~1,6 – 1,7 W/m\u00B2K" },
      { label: "Chiusura", value: "Multipoint" },
    ],
    colors: "Bianco, effetto legno (rovere dorato, noce, mogano), antracite, bicolore",
    features: ["Design classico con vetrocamera", "Profilo PVC 5 camere", "Chiusura multipoint di serie", "Soglia ribassata"],
  },
  "Oknoplast — Torino": {
    name: "Torino",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino d'ingresso in PVC con pannello pieno e fresature decorative orizzontali. Linea sobria ed elegante, ideale per contesti residenziali contemporanei. Profilo a 5 camere da 70 mm e chiusura multipoint.",
    highlight: "Pannello pieno con fresature — eleganza sobria in PVC",
    specs: [
      { label: "Materiale", value: "PVC a 5 camere" },
      { label: "Profilo", value: "70 mm" },
      { label: "Pannello", value: "24 mm pieno con fresature" },
      { label: "Trasmittanza Uw", value: "~1,6 – 1,7 W/m\u00B2K" },
      { label: "Chiusura", value: "Multipoint" },
      { label: "Cerniere", value: "Regolabili 3D" },
    ],
    colors: "Bianco, effetto legno (rovere dorato, noce, mogano), antracite, bicolore",
    features: ["Fresature decorative orizzontali", "Pannello pieno isolante", "Chiusura multipoint", "Cerniere regolabili 3D"],
  },
  "Oknoplast — Milano": {
    name: "Milano",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Portoncino d'ingresso in PVC dal design moderno e minimale con ampio inserto vetrato laterale che dona luminosit\u00E0 all'ingresso. Profilo a 5 camere da 70 mm con doppio vetro 24 mm e chiusura multipoint.",
    highlight: "Vetrata laterale per massima luminosit\u00E0 — design moderno in PVC",
    specs: [
      { label: "Materiale", value: "PVC a 5 camere" },
      { label: "Profilo", value: "70 mm" },
      { label: "Pannello", value: "24 mm" },
      { label: "Vetrocamera", value: "24 mm doppio vetro" },
      { label: "Trasmittanza Uw", value: "~1,6 – 1,7 W/m\u00B2K" },
      { label: "Chiusura", value: "Multipoint" },
    ],
    colors: "Bianco, effetto legno, antracite, bicolore",
    features: ["Inserto vetrato laterale", "Design moderno e luminoso", "Chiusura multipoint", "Profilo PVC 5 camere"],
  },
  "Oknoplast — Venezia": {
    name: "Venezia",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino d'ingresso in PVC con doppio pannello vetrato decorativo che richiama l'eleganza delle porte veneziane. Profilo a 5 camere da 70 mm e doppio vetro da 24 mm per un perfetto equilibrio tra estetica e isolamento.",
    highlight: "Doppio pannello vetrato decorativo — charme veneziano in PVC",
    specs: [
      { label: "Materiale", value: "PVC a 5 camere" },
      { label: "Profilo", value: "70 mm" },
      { label: "Pannello", value: "24 mm" },
      { label: "Vetrocamera", value: "24 mm doppio vetro (x2)" },
      { label: "Trasmittanza Uw", value: "~1,6 – 1,7 W/m\u00B2K" },
      { label: "Chiusura", value: "Multipoint" },
    ],
    colors: "Bianco, effetto legno (rovere dorato, noce), antracite, bicolore",
    features: ["Doppio pannello vetrato", "Estetica elegante tradizionale", "Chiusura multipoint", "Doppio vetro isolante"],
  },
  "Oknoplast — Roma": {
    name: "Roma",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Portoncino d'ingresso in PVC con pannello pieno e bugne classiche che conferiscono un aspetto solido e autorevole. Pensato per ingressi di rappresentanza, unisce il fascino tradizionale alla praticit\u00E0 del PVC.",
    highlight: "Bugne classiche su PVC — ingresso di rappresentanza",
    specs: [
      { label: "Materiale", value: "PVC a 5 camere" },
      { label: "Profilo", value: "70 mm" },
      { label: "Pannello", value: "24 mm pieno con bugne" },
      { label: "Trasmittanza Uw", value: "~1,6 – 1,7 W/m\u00B2K" },
      { label: "Chiusura", value: "Multipoint" },
      { label: "Cerniere", value: "Regolabili 3D" },
    ],
    colors: "Bianco, effetto legno (rovere dorato, noce, mogano), antracite, bicolore",
    features: ["Bugne classiche decorative", "Aspetto solido e autorevole", "Chiusura multipoint", "Manutenzione ridotta in PVC"],
  },

  /* ── Porte Cosmo PVC — con decorazioni alluminio ────────── */

  "Oknoplast — Cosmo Quarzite": {
    name: "Cosmo Quarzite",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "Porta esterna in PVC della linea Cosmo con pannello HPL pieno e finitura ispirata alla quarzite naturale. Profilo 70 mm, pannello 36 mm ad alta densit\u00E0, chiusura a 3 punti e cerniere regolabili 3D.",
    highlight: "Finitura quarzite su HPL 36 mm — eleganza minerale",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL alta densit\u00E0" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
      { label: "Decorazioni", value: "Nessuna (pannello pieno)" },
    ],
    colors: "Finiture pietra naturale, antracite, RAL, bicolore",
    features: ["Pannello HPL 36 mm alta densit\u00E0", "Finitura effetto quarzite", "Chiusura 3 punti", "Cerniere regolabili 3D"],
  },
  "Oknoplast — Cosmo Orientite": {
    name: "Cosmo Orientite",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Porta esterna Cosmo con decorazioni in alluminio e inserto vetrato verticale che crea un gioco di luce e trasparenza. Pannello HPL 36 mm con doppio vetro 22 mm per isolamento e luminosit\u00E0.",
    highlight: "Vetro + alluminio — gioco di luce su HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Vetrocamera", value: "22 mm doppio vetro" },
      { label: "Decorazioni", value: "Alluminio + vetro" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Decorazioni in alluminio", "Inserto vetrato 22 mm", "Pannello HPL 36 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Manganite": {
    name: "Cosmo Manganite",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Porta esterna Cosmo con decorazioni in alluminio e vetro che creano un motivo geometrico moderno. Pannello HPL 36 mm, profilo PVC 70 mm e isolamento termico fino a 1,2 W/m\u00B2K.",
    highlight: "Geometrie alluminio e vetro — design moderno su PVC",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Vetrocamera", value: "22 mm doppio vetro" },
      { label: "Decorazioni", value: "Alluminio + vetro" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Motivo geometrico moderno", "Decorazioni alluminio + vetro", "Pannello HPL 36 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Froodite": {
    name: "Cosmo Froodite",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Porta esterna Cosmo con inserto vetrato e decorazioni in alluminio dal design elegante. Pannello HPL 36 mm ad alta densit\u00E0 con vetrocamera 22 mm per un perfetto equilibrio tra estetica e prestazioni.",
    highlight: "Eleganza in alluminio e vetro — HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Vetrocamera", value: "22 mm doppio vetro" },
      { label: "Decorazioni", value: "Alluminio + vetro" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Design elegante alluminio + vetro", "HPL alta densit\u00E0", "Vetrocamera 22 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Dellaite": {
    name: "Cosmo Dellaite",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Porta esterna Cosmo con decorazioni in alluminio e inserto vetrato dal design contemporaneo e raffinato. Pannello HPL 36 mm, isolamento fino a 1,2 W/m\u00B2K e chiusura antieffrazione a 3 punti.",
    highlight: "Contemporaneo e raffinato — alluminio, vetro e HPL",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Vetrocamera", value: "22 mm doppio vetro" },
      { label: "Decorazioni", value: "Alluminio + vetro" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Decorazioni contemporanee", "Inserto vetrato", "Pannello HPL 36 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Barite": {
    name: "Cosmo Barite",
    brand: "Oknoplast",
    segment: "Premium",
    description:
      "Porta esterna Cosmo con pannello HPL pieno e decorazioni in alluminio senza vetro, per massima privacy e isolamento. Design solido ispirato alla barite minerale, con chiusura antieffrazione a 3 punti.",
    highlight: "HPL pieno + alluminio — massima privacy e solidit\u00E0",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL pieno" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Decorazioni", value: "Alluminio (senza vetro)" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Pannello pieno senza vetro", "Decorazioni in alluminio", "Massima privacy", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Heyite": {
    name: "Cosmo Heyite",
    brand: "Oknoplast",
    segment: "Design",
    description:
      "Porta esterna Cosmo con inserto vetrato e decorazioni in alluminio dal design sofisticato. Pannello HPL 36 mm con vetrocamera 22 mm, chiusura antieffrazione e cerniere regolabili 3D.",
    highlight: "Sofisticato con vetro e alluminio — Cosmo HPL",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Vetrocamera", value: "22 mm doppio vetro" },
      { label: "Decorazioni", value: "Alluminio + vetro" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "RAL standard, effetto legno, antracite, bicolore",
    features: ["Design sofisticato", "Alluminio + vetro", "HPL 36 mm", "Chiusura 3 punti"],
  },

  /* ── Porte Cosmo PVC — rivestimento PVC ─────────────────── */

  "Oknoplast — Cosmo Turchese": {
    name: "Cosmo Turchese",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento in PVC e finitura dal nome evocativo. Pannello HPL 36 mm, profilo 70 mm a 5 camere. Design pulito e lineare, ideale per ingressi moderni e funzionali.",
    highlight: "Finitura PVC essenziale — HPL 36 mm, design lineare",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Rivestimento PVC resistente", "Pannello HPL 36 mm", "Design lineare", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Perla": {
    name: "Cosmo Perla",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento in PVC e finitura elegante. Pannello HPL 36 mm per isolamento ottimale, chiusura antieffrazione a 3 punti e manutenzione praticamente nulla.",
    highlight: "Eleganza PVC senza manutenzione — HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Finitura elegante PVC", "Manutenzione ridotta", "HPL 36 mm isolante", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Giada": {
    name: "Cosmo Giada",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento PVC dal design essenziale e raffinato. Pannello HPL 36 mm ad alta densit\u00E0, profilo 70 mm a 5 camere per isolamento termico e acustico ottimali.",
    highlight: "Essenziale e raffinato — PVC + HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Design essenziale e raffinato", "HPL alta densit\u00E0", "Isolamento termoacustico", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Fluorite": {
    name: "Cosmo Fluorite",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento PVC e pannello HPL 36 mm. Design contemporaneo e pulito con linee minimali, chiusura antieffrazione a 3 punti e cerniere regolabili.",
    highlight: "Contemporaneo e pulito — PVC con HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Linee minimali contemporanee", "Pannello HPL 36 mm", "Cerniere regolabili", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Azzurrite": {
    name: "Cosmo Azzurrite",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento PVC resistente agli agenti atmosferici. Pannello HPL 36 mm, profilo 70 mm e chiusura a 3 punti per un ingresso sicuro e duraturo.",
    highlight: "PVC resistente alle intemperie — HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Resistenza intemperie", "PVC duraturo", "HPL 36 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Ambra": {
    name: "Cosmo Ambra",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento PVC e tonalità calde ispirate all'ambra. Pannello HPL 36 mm per isolamento e robustezza, chiusura antieffrazione a 3 punti.",
    highlight: "Tonalit\u00E0 calde su PVC — HPL 36 mm isolante",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, tonalit\u00E0 calde, bicolore",
    features: ["Tonalit\u00E0 calde", "PVC resistente", "HPL 36 mm", "Chiusura 3 punti"],
  },
  "Oknoplast — Cosmo Acquamarina": {
    name: "Cosmo Acquamarina",
    brand: "Oknoplast",
    segment: "Classic",
    description:
      "Porta esterna Cosmo con rivestimento PVC e design fresco e contemporaneo. Pannello HPL 36 mm, profilo 70 mm a 5 camere, chiusura antieffrazione a 3 punti per un ingresso sicuro e di stile.",
    highlight: "Design fresco e contemporaneo — PVC + HPL 36 mm",
    specs: [
      { label: "Linea", value: "Cosmo" },
      { label: "Profilo", value: "70 mm PVC a 5 camere" },
      { label: "Pannello", value: "36 mm HPL" },
      { label: "Trasmittanza Uw", value: "fino a 1,2 W/m\u00B2K" },
      { label: "Rivestimento", value: "PVC" },
      { label: "Chiusura", value: "3 punti antieffrazione" },
    ],
    colors: "Bianco, antracite, effetto legno, bicolore",
    features: ["Design fresco contemporaneo", "PVC a 5 camere", "HPL 36 mm", "Chiusura 3 punti"],
  },
};

/* ── PERSIANE — Erreci / Persit / Korus ──────────────────────── */

export const persianeDetails: Record<string, ProductDetail> = {
  "Erreci — Maxima Plus": {
    name: "Maxima Plus",
    brand: "Erreci",
    segment: "Sicurezza blindata",
    description:
      "Persiana blindata in alluminio con profili maggiorati che nascondono una griglia in acciaio inox completamente invisibile dall'esterno. Serratura a 3 punti con cilindro europeo antiperforazione. Certificata Classe 3 antieffrazione dall'Istituto Giordano.",
    highlight: "Blindatura nascosta in acciaio inox — Classe 3 antieffrazione certificata",
    specs: [
      { label: "Materiale", value: "Alluminio estruso maggiorato + blindatura acciaio inox" },
      { label: "Classe antieffrazione", value: "Classe 3 (certificata Istituto Giordano)" },
      { label: "Serratura", value: "Ad infilare, 3 punti di chiusura, corsa 25 mm" },
      { label: "Cilindro", value: "Mezzo cilindro europeo antiperforazione" },
      { label: "Cerniere", value: "Acciaio ad alta resistenza meccanica" },
      { label: "Verniciatura", value: "A polvere Classe 2, resistenza UV" },
    ],
    colors: "Gamma RAL completa, finiture effetto legno, colori standard a catalogo",
    features: ["Blindatura nascosta", "Rostri antistrappo", "Lamelle orientabili ovali o trapezoidali", "Versioni ad arco"],
  },
  "Erreci — Maxima Light": {
    name: "Maxima Light",
    brand: "Erreci",
    segment: "Sicurezza",
    description:
      "Persiana in alluminio con blindatura in acciaio inox nascosta, protezione Classe 2 con peso ridotto. Ideale per installazioni su edifici esistenti dove il carico sui cardini è un fattore critico.",
    highlight: "Blindatura leggera in acciaio inox — Classe 2, ideale per ristrutturazioni",
    specs: [
      { label: "Materiale", value: "Alluminio estruso maggiorato + acciaio inox" },
      { label: "Classe antieffrazione", value: "Classe 2" },
      { label: "Serratura", value: "Di sicurezza multipunto" },
      { label: "Cerniere", value: "Acciaio ad alta resistenza" },
      { label: "Lamelle", value: "Fisse aperte o orientabili" },
      { label: "Verniciatura", value: "A polvere Classe 2, resistenza UV e salsedine" },
    ],
    colors: "Gamma RAL completa, finiture effetto legno",
    features: ["Blindatura nascosta", "Peso ridotto", "Lamelle orientabili", "Adatta a ristrutturazioni"],
  },
  "Persit — Elisa": {
    name: "Elisa",
    brand: "Persit",
    segment: "Classica su telaio",
    description:
      "Persiana battente su telaio dalle forme squadrate con anta a sormonto. Telaio standard con aletta 40 mm, disponibile con aletta 70 mm o telaio storico. Lamelle orientabili con maniglieria cremonese in tinta. Disponibile in versione RC2 con serratura a 5 punti.",
    highlight: "Design classico con anta a sormonto — disponibile antieffrazione RC2",
    specs: [
      { label: "Materiale", value: "Alluminio estruso verniciato a polvere" },
      { label: "Telaio", value: "Aletta 40 mm standard, opzionale 70 mm o storico" },
      { label: "Lamelle", value: "Orientabili con meccanismi in tinta" },
      { label: "Maniglieria", value: "Cremonese di serie, spagnoletta storica opzionale" },
      { label: "Versione sicurezza", value: "RC2 con serratura a 5 punti e barre acciaio" },
      { label: "Motorizzazione", value: "PERSINT disponibile" },
    ],
    colors: "RAL Raffaello, effetti legno a catalogo, qualunque RAL su richiesta",
    features: ["Battente su telaio", "Anta a sormonto", "Lamelle orientabili", "Versione RC2", "Motorizzabile"],
  },
  "Persit — Clara": {
    name: "Clara",
    brand: "Persit",
    segment: "Moderna complanare",
    description:
      "Persiana battente con telaio e anta complanare dal design contemporaneo e lineare. Le forme squadrate e la complanarità donano un'estetica moderna ed elegante. Telaio standard con aletta 35 mm, opzionale 70 mm.",
    highlight: "Anta complanare al telaio — design moderno e linee pulite",
    specs: [
      { label: "Materiale", value: "Alluminio estruso verniciato a polvere" },
      { label: "Telaio", value: "Aletta 35 mm standard, opzionale 70 mm" },
      { label: "Design", value: "Complanare — anta e telaio sullo stesso piano" },
      { label: "Lamelle", value: "Orientabili con meccanismi in tinta" },
      { label: "Maniglieria", value: "Cremonese in tinta abbinata" },
      { label: "Motorizzazione", value: "PERSINT disponibile" },
    ],
    colors: "RAL Raffaello, effetti legno a catalogo, qualunque RAL su richiesta",
    features: ["Battente complanare", "Design contemporaneo", "Profilo squadrato", "Motorizzabile"],
  },
  "Korus — SK45 Dione": {
    name: "SK45 Dione",
    brand: "Korus",
    segment: "Classica",
    description:
      "Persiana in alluminio con telaio rustico e profilo anta 45 mm. Verniciatura esclusiva ThermoReflex con pigmenti termoriflettenti che respingono i raggi infrarossi, migliorando l'isolamento termico estivo. Trattamento anticorrosivo SEASIDE di serie.",
    highlight: "Verniciatura ThermoReflex termoriflettente — garanzia 30 anni",
    specs: [
      { label: "Materiale", value: "Alluminio estruso 100% Made in Italy" },
      { label: "Profilo anta", value: "45 mm" },
      { label: "Telaio", value: "Rustico" },
      { label: "Lamelle", value: "Classica fissa o orientabile a goccia" },
      { label: "Verniciatura", value: "ThermoReflex termoriflettente a polvere" },
      { label: "Garanzia", value: "30 anni sulla verniciatura" },
    ],
    colors: "Gamma RAL completa, effetti legno, colori personalizzati",
    features: ["Telaio rustico", "Lamelle orientabili a goccia", "ThermoReflex", "SEASIDE anticorrosione", "Garanzia 30 anni"],
  },
  "Korus — Crono": {
    name: "Crono",
    brand: "Korus",
    segment: "Premium",
    description:
      "Persiana in alluminio con profilo anta 53 mm per massima robustezza. Disponibile in 7 stili di lamella: classica, a goccia, fiorentina, storica, chiusa, verticale e ovale orientabile. Verniciatura ThermoReflex e trattamento SEASIDE di serie.",
    highlight: "Profilo 53 mm, 7 stili di lamella — la persiana Korus più versatile",
    specs: [
      { label: "Materiale", value: "Alluminio estruso 100% Made in Italy" },
      { label: "Profilo anta", value: "53 mm" },
      { label: "Lamelle", value: "Classica, goccia, fiorentina, storica, chiusa, verticale, ovale" },
      { label: "Verniciatura", value: "ThermoReflex termoriflettente a polvere" },
      { label: "Trattamento", value: "SEASIDE anticorrosivo certificato Qualicoat" },
      { label: "Garanzia", value: "30 anni sulla verniciatura" },
    ],
    colors: "Gamma RAL completa, effetti legno, colori personalizzati",
    features: ["7 stili di lamella", "Versione Security disponibile", "ThermoReflex", "SEASIDE anticorrosione", "Garanzia 30 anni"],
  },
};

/* ── FRANGISOLE — Lupak Metal ────────────────────────────────── */

export const frangisoleDetails: Record<string, ProductDetail> = {
  "Lupak — Lume Pro": {
    name: "Lume Pro",
    brand: "Lupak",
    segment: "Top di gamma",
    description:
      "Evoluzione del frangisole a catena Lume con lamella in alluminio estruso da 13/10 mm e bordo anti-riflesso che ottimizza la gestione della luce naturale. Resistenza al vento 150 km/h, parti mobili interamente in acciaio inox.",
    highlight: "Resistenza al vento 150 km/h, bordo anti-riflesso — oscuramento superiore",
    specs: [
      { label: "Tipologia", value: "Sistema a catena orientabile e impacchettabile" },
      { label: "Lamella", value: "Alluminio estruso 13/10 mm con bordo anti-riflesso" },
      { label: "Orientamento", value: "Da 0° a 87° in qualsiasi posizione" },
      { label: "Resistenza al vento", value: "150 km/h (su 3000×3000 mm)" },
      { label: "Parti mobili", value: "Interamente in acciaio inox, garanzia 5 anni" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Bordo anti-riflesso", "Fissaggio lamella invisibile", "Motorizzabile con sensori", "Guarnizione settoriale"],
  },
  "Lupak — Lume Esse": {
    name: "Lume Esse",
    brand: "Lupak",
    segment: "Premium",
    description:
      "Frangisole a catena con lamelle in alluminio estruso 13/10 mm per grandi dimensioni fino a 9 m². Fissaggio lamella completamente invisibile dall'esterno per una facciata pulita e contemporanea. Oscuramento fino al 92%.",
    highlight: "Fino a 9 m², oscuramento 92% — fissaggio invisibile dall'esterno",
    specs: [
      { label: "Tipologia", value: "Sistema a catena orientabile e impacchettabile" },
      { label: "Lamella", value: "Alluminio estruso 13/10 mm" },
      { label: "Superficie massima", value: "9 m²" },
      { label: "Resistenza al vento", value: "140 km/h (930 Pa su 3000×3000 mm)" },
      { label: "Oscuramento", value: "Fino al 92%" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Fissaggio invisibile", "Guide autoportanti", "Motorizzabile con sensori", "Grandi superfici"],
  },
  "Lupak — Lume Light": {
    name: "Lume Light",
    brand: "Lupak",
    segment: "Residenziale",
    description:
      "Frangisole a catena leggero con lamelle in alluminio profilato 0,75 mm, ideale per il residenziale. Chiusura completa delle lamelle in posizione abbassata per privacy e oscuramento totale. Meccanismo di sollevamento silenziato.",
    highlight: "Leggero e compatto 120 km/h — meccanismo silenziato, ideale per il residenziale",
    specs: [
      { label: "Tipologia", value: "Sistema a catena orientabile e impacchettabile" },
      { label: "Lamella", value: "Alluminio profilato 0,75 mm" },
      { label: "Orientamento", value: "Da 35° a 80°; 0° a −80° abbassata" },
      { label: "Resistenza al vento", value: "120 km/h (su 3000×3000 mm)" },
      { label: "Chiusura", value: "Completa in posizione abbassata" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Leggero e compatto", "Sollevamento silenziato", "Chiusura completa", "Motorizzabile"],
  },
  "Lupak — Filo 90": {
    name: "Filo 90",
    brand: "Lupak",
    segment: "Tecnico",
    description:
      "Frangisole a filo con lamella a Z da 92 mm e guarnizione in gomma che riduce le infiltrazioni di luce e migliora l'oscuramento fino al 90%. Superficie copribile fino a 12,5 m², rotazione lame 180°.",
    highlight: "Lamella a Z con guarnizione — oscuramento 90%, superficie fino a 12,5 m²",
    specs: [
      { label: "Tipologia", value: "Sistema a filo impacchettabile" },
      { label: "Lamella", value: "Lega di alluminio a Z, 92 mm, 0,47 mm" },
      { label: "Superficie massima", value: "12,5 m²" },
      { label: "Oscuramento", value: "Fino al 90%" },
      { label: "Rotazione lame", value: "180°" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Guarnizione anti-infiltrazione", "Design a Z", "Grandi aperture", "Motorizzabile"],
  },
  "Lupak — Filo 65": {
    name: "Filo 65",
    brand: "Lupak",
    segment: "Compatto",
    description:
      "Il più compatto della gamma: lamella curva a coppo da 65 mm con vernice antigraffio su entrambi i lati. Rotazione 180°, guide laterali anodizzate con gommini antirumore. Ideale per aperture di dimensioni contenute.",
    highlight: "Il più compatto — lamella curva a coppo, vernice antigraffio bilaterale",
    specs: [
      { label: "Tipologia", value: "Sistema a filo impacchettabile" },
      { label: "Lamella", value: "Lega di alluminio curva a coppo, 65 mm, 0,45 mm" },
      { label: "Finitura", value: "Termolaccatura antigraffio su entrambi i lati" },
      { label: "Rotazione lame", value: "180°" },
      { label: "Guide laterali", value: "20×21 mm anodizzate con gommini antirumore" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Compatto", "Vernice antigraffio bilaterale", "Gommini antirumore", "Motorizzabile"],
  },
  "Lupak — Lume": {
    name: "Lume",
    brand: "Lupak",
    segment: "Premium",
    description:
      "Il frangisole a catena originale Lupak con lamella in alluminio estruso da 13/10 mm e sistema di aggancio invisibile dall'esterno. Orientamento e chiusura delle lame in qualsiasi posizione intermedia. Resistenza al vento fino a 140 km/h.",
    highlight: "L'originale a catena — lamella estrusa 13/10 mm, resistenza 140 km/h",
    specs: [
      { label: "Tipologia", value: "Sistema a catena orientabile e impacchettabile" },
      { label: "Lamella", value: "Alluminio estruso 13/10 mm" },
      { label: "Orientamento", value: "Chiusura in qualsiasi posizione intermedia" },
      { label: "Resistenza al vento", value: "140 km/h (su 3000×3000 mm)" },
      { label: "Aggancio", value: "Sistema invisibile dall'esterno" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Aggancio invisibile", "Guide autoportanti", "Motorizzabile con sensori", "Resistenza 140 km/h"],
  },
  "Lupak — Filo 90 Esse": {
    name: "Filo 90 Esse",
    brand: "Lupak",
    segment: "Tecnico",
    description:
      "Variante del Filo 90 con lamella a profilo S (Esse) da 90 mm per un effetto estetico più morbido e armonioso. Disponibile con manovra a motore o argano, in versione standard e a cavo.",
    highlight: "Profilo S per estetica superiore — stesse prestazioni del Filo 90",
    specs: [
      { label: "Tipologia", value: "Sistema a filo impacchettabile" },
      { label: "Lamella", value: "Lega di alluminio profilo S (Esse), 90 mm" },
      { label: "Manovra", value: "Motore o argano, versione standard e a cavo" },
      { label: "Rotazione lame", value: "180°" },
      { label: "Estetica", value: "Profilo S per linee morbide e armoniche" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Profilo S morbido", "Doppia versione STD/cavo", "Grandi aperture", "Motorizzabile"],
  },
  "Lupak — Filo 80": {
    name: "Filo 80",
    brand: "Lupak",
    segment: "Versatile",
    description:
      "Frangisole a filo con lamella a C da 80 mm, versatile e adatto a molteplici applicazioni residenziali e commerciali. Disponibile in versione standard e a cavo, con manovra a motore o argano.",
    highlight: "Lamella a C versatile — ideale per residenziale e commerciale",
    specs: [
      { label: "Tipologia", value: "Sistema a filo impacchettabile" },
      { label: "Lamella", value: "Lega di alluminio profilo C, 80 mm" },
      { label: "Versioni", value: "80MM STD e 80MM Cavo" },
      { label: "Manovra", value: "Motore o argano" },
      { label: "Rotazione lame", value: "180°" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Profilo C versatile", "Doppia versione STD/cavo", "Motorizzabile", "Ingombro ridotto"],
  },
  "Lupak — Filo 70": {
    name: "Filo 70",
    brand: "Lupak",
    segment: "Intermedio",
    description:
      "Frangisole a filo con lamella a Z da 70 mm in alluminio estruso, ideale per grandi aperture grazie ai ridotti ingombri. Disponibile in versione standard e a cavo, con manovra a motore o argano.",
    highlight: "Lamella a Z 70 mm — ingombri ridotti per grandi aperture",
    specs: [
      { label: "Tipologia", value: "Sistema a filo impacchettabile" },
      { label: "Lamella", value: "Alluminio estruso profilo Z, 70 mm" },
      { label: "Versioni", value: "70MM STD e 70MM Cavo" },
      { label: "Manovra", value: "Motore o argano" },
      { label: "Rotazione lame", value: "180°" },
      { label: "Normative", value: "UNI EN 13659, UNI EN 1932" },
    ],
    colors: "Gamma RAL completa, marmorizzate, effetto legno, metallizzate, sublimazione",
    features: ["Profilo Z compatto", "Ingombri ridotti", "Grandi aperture", "Motorizzabile"],
  },
  "Lupak — Lupafix IC120": {
    name: "Lupafix IC120",
    brand: "Lupak",
    segment: "Sistema di fissaggio",
    description:
      "Sistema di fissaggio a incasso per frangisole a catena. Montaggio filo-muro per un aspetto integrato e pulito. Registrazione telescopica delle guide, cappette terminali in acciaio inox, verniciabile a polvere per abbinarsi alla facciata.",
    highlight: "Fissaggio a incasso filo-muro — aspetto integrato e minimale",
    specs: [
      { label: "Tipologia", value: "Sistema di fissaggio a incasso (catena)" },
      { label: "Montaggio", value: "Filo-muro, registrazione telescopica guide" },
      { label: "Materiale", value: "Alluminio verniciabile a polvere" },
      { label: "Cappette", value: "Acciaio inox (senza soglia)" },
      { label: "Compatibilità", value: "Sistemi a catena Lume, Lume Pro, Lume Esse, Lume Light" },
    ],
    colors: "Verniciabile a polvere in qualsiasi colore RAL",
    features: ["Incasso filo-muro", "Registrazione telescopica", "Kit LED compatibile", "Senza soglia"],
  },
  "Lupak — Lupafix FC180": {
    name: "Lupafix FC180",
    brand: "Lupak",
    segment: "Sistema di fissaggio",
    description:
      "Sistema di fissaggio frontale per frangisole a catena. Montaggio a vista con profilo continuo per un controllo della luce ottimale e un'integrazione estetica in facciata. Meccanismo telescopico di regolazione.",
    highlight: "Fissaggio frontale con profilo continuo — controllo luce ottimale",
    specs: [
      { label: "Tipologia", value: "Sistema di fissaggio frontale (catena)" },
      { label: "Montaggio", value: "Frontale a vista, profilo di fissaggio continuo" },
      { label: "Materiale", value: "Alluminio verniciabile a polvere" },
      { label: "Regolazione", value: "Meccanismo telescopico" },
      { label: "Compatibilità", value: "Sistemi a catena Lume, Lume Pro, Lume Esse, Lume Light" },
    ],
    colors: "Verniciabile a polvere in qualsiasi colore RAL",
    features: ["Montaggio frontale", "Profilo continuo", "Kit LED compatibile", "Regolazione telescopica"],
  },
  "Lupak — Lupafix FF108": {
    name: "Lupafix FF108",
    brand: "Lupak",
    segment: "Sistema di fissaggio",
    description:
      "Sistema di fissaggio dedicato ai frangisole a filo. Installazione semplificata senza soglia, verniciabile a polvere per personalizzazione cromatica. Compatibile con l'installazione del Kit LED.",
    highlight: "Fissaggio per sistemi a filo — installazione semplificata senza soglia",
    specs: [
      { label: "Tipologia", value: "Sistema di fissaggio (filo)" },
      { label: "Montaggio", value: "Senza soglia, installazione semplificata" },
      { label: "Materiale", value: "Alluminio verniciabile a polvere" },
      { label: "Compatibilità", value: "Sistemi a filo Filo 65, 70, 80, 90" },
    ],
    colors: "Verniciabile a polvere in qualsiasi colore RAL",
    features: ["Per sistemi a filo", "Senza soglia", "Kit LED compatibile", "Verniciabile a polvere"],
  },
};

/* ── TAPPARELLE — Pasini ─────────────────────────────────────── */

export const tapparelleDetails: Record<string, ProductDetail> = {
  /* ── Alluminio ─────────────────────────── */
  "Pasini — Roll 55": {
    name: "Roll 55",
    brand: "Pasini",
    segment: "Classic",
    description:
      "L'avvolgibile più venduto della gamma Pasini. Profilo in alluminio preverniciato 14×55 mm con anima in poliuretano espanso a media densità. Struttura arcuata con nervature longitudinali e protezione antigraffio trasparente di serie.",
    highlight: "Il best-seller Pasini — massimo rapporto qualità-prezzo, consegna ONEday",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU media densità" },
      { label: "Profilo", value: "14 × 55 mm — spessore 0,36 mm" },
      { label: "Peso", value: "~3,7 kg/m²" },
      { label: "Larghezza massima", value: "3.900 mm" },
      { label: "Lamelle al m²", value: "18,2" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "24 colori pieni, 8 effetto legno, 4 metallizzate Raffaello",
    features: ["Protezione antigraffio di serie", "Nervature longitudinali", "Consegna ONEday 24h", "Motorizzabile"],
  },
  "Pasini — Roll 45": {
    name: "Roll 45",
    brand: "Pasini",
    segment: "Classic",
    description:
      "Avvolgibile compatto con profilo ridotto 9×45 mm, perfetto per cassonetti di dimensioni contenute e ristrutturazioni con spazi limitati. Leggero (2,9 kg/m²) per manovre agevoli anche manuali.",
    highlight: "Profilo compatto 9×45 mm — la soluzione ideale per cassonetti ridotti",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU media densità" },
      { label: "Profilo", value: "9 × 45 mm — spessore 0,33 mm" },
      { label: "Peso", value: "~2,9 kg/m²" },
      { label: "Larghezza massima", value: "3.200 mm" },
      { label: "Lamelle al m²", value: "22,2" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "14 colori pieni, effetto legno chiaro e scuro, 4 metallizzate Raffaello",
    features: ["Ultra-compatto", "Peso contenuto", "Protezione antigraffio", "Consegna ONEday 24h"],
  },
  "Pasini — Maxi Roll 55": {
    name: "Maxi Roll 55",
    brand: "Pasini",
    segment: "Premium",
    description:
      "Avvolgibile ad alte prestazioni con poliuretano espanso ad alta densità per il massimo isolamento termico. Profilo 14×55 mm rinforzato, progettato per grandi luci fino a 4 metri.",
    highlight: "Alta densità per grandi luci — isolamento superiore fino a 4 metri",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU alta densità" },
      { label: "Profilo", value: "14 × 55 mm — spessore 0,36 mm" },
      { label: "Peso", value: "~5,1 kg/m²" },
      { label: "Larghezza massima", value: "4.000 mm" },
      { label: "Lamelle al m²", value: "18,2" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "18 colori pieni, 7 effetto legno, 4 metallizzate Raffaello",
    features: ["PU alta densità", "Grandi aperture fino a 4 m", "Protezione antigraffio", "Consegna ONEday 24h"],
  },
  "Pasini — Roll 50 Air": {
    name: "Roll 50 Air",
    brand: "Pasini",
    segment: "Design",
    description:
      "Avvolgibile innovativo con asole longitudinali da 180 mm che garantiscono luce e aerazione naturale anche a tapparella abbassata. Privacy mantenuta: la luce entra ma lo sguardo resta fuori.",
    highlight: "Luce e aerazione a tapparella chiusa — asole da 180 mm",
    specs: [
      { label: "Materiale", value: "Alluminio con poliuretano espanso" },
      { label: "Profilo", value: "12 × 50 mm — spessore ~0,50 mm" },
      { label: "Peso", value: "~5,0 kg/m²" },
      { label: "Larghezza massima", value: "4.200 mm" },
      { label: "Asole di aerazione", value: "180 mm (10× lo standard)" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "25+ colori pieni, 8 effetto legno, 3 metallizzate Raffaello",
    features: ["Asole 180 mm", "Luminosità anche chiusa", "Privacy mantenuta", "Domotica compatibile"],
  },
  "Pasini — Roll 55 Eco": {
    name: "Roll 55 Eco",
    brand: "Pasini",
    segment: "Classic",
    description:
      "Versione economica del Roll 55 con stesse dimensioni 14×55 mm e protezione antigraffio. Anima in poliuretano espanso a media densità, ideale per grandi forniture e interventi di ristrutturazione con budget contenuto.",
    highlight: "Prestazioni Roll 55 a prezzo competitivo — la scelta smart",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU media densità" },
      { label: "Profilo", value: "14 × 55 mm" },
      { label: "Peso", value: "~3,7 kg/m²" },
      { label: "Larghezza massima", value: "3.900 mm" },
      { label: "Lamelle al m²", value: "18,2" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Gamma colori pieni, effetto legno",
    features: ["Protezione antigraffio", "Rapporto qualità-prezzo ottimale", "Consegna ONEday 24h", "Motorizzabile"],
  },
  "Pasini — Roll 39": {
    name: "Roll 39",
    brand: "Pasini",
    segment: "Compact",
    description:
      "Avvolgibile ultra-compatto con profilo di soli 9×39 mm, il più piccolo della gamma Pasini. Soluzione ideale per cassonetti mini e applicazioni dove lo spazio è ridotto al minimo.",
    highlight: "Il più compatto della gamma — profilo 9×39 mm per cassonetti mini",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU media densità" },
      { label: "Profilo", value: "9 × 39 mm" },
      { label: "Peso", value: "~2,5 kg/m²" },
      { label: "Larghezza massima", value: "2.500 mm" },
      { label: "Lamelle al m²", value: "25,6" },
      { label: "Movimentazione", value: "Cinghia o motore tubolare" },
    ],
    colors: "Colori pieni standard, effetto legno",
    features: ["Ultra-compatto", "Diametro avvolgimento minimo", "Ideale per ristrutturazioni", "Motorizzabile"],
  },
  "Pasini — Maxi Roll 55 TP": {
    name: "Maxi Roll 55 TP",
    brand: "Pasini",
    segment: "Premium",
    description:
      "Versione top di gamma del Maxi Roll 55 con terminale in alluminio estruso e guarnizione in gomma per la massima tenuta all'aria e all'acqua. Performance superiori per grandi luci.",
    highlight: "Terminale estruso con guarnizione — il top della gamma Maxi",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU alta densità" },
      { label: "Profilo", value: "14 × 55 mm — terminale estruso" },
      { label: "Peso", value: "~5,3 kg/m²" },
      { label: "Larghezza massima", value: "4.000 mm" },
      { label: "Lamelle al m²", value: "18,2" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "18 colori pieni, 7 effetto legno, 4 metallizzate Raffaello",
    features: ["Terminale estruso", "Guarnizione in gomma", "Tenuta aria/acqua", "PU alta densità"],
  },
  "Pasini — Maxi Roll 50 Air": {
    name: "Maxi Roll 50 Air",
    brand: "Pasini",
    segment: "Design",
    description:
      "Combinazione unica: le asole di aerazione del Roll 50 Air con le prestazioni premium della serie Maxi. Luce e ventilazione naturale anche a tapparella chiusa, con coibentazione ad alta densità.",
    highlight: "Aerazione naturale + coibentazione premium — il meglio dei due mondi",
    specs: [
      { label: "Materiale", value: "Alluminio con PU alta densità" },
      { label: "Profilo", value: "12 × 50 mm — asole di aerazione" },
      { label: "Peso", value: "~5,2 kg/m²" },
      { label: "Larghezza massima", value: "4.200 mm" },
      { label: "Asole di aerazione", value: "180 mm" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "Colori pieni, effetto legno, metallizzate Raffaello",
    features: ["Asole 180 mm", "PU alta densità", "Luce anche chiusa", "Domotica compatibile"],
  },
  "Pasini — Maxi Roll 41": {
    name: "Maxi Roll 41",
    brand: "Pasini",
    segment: "Premium",
    description:
      "Avvolgibile ad alta densità con profilo compatto da 41 mm. Poliuretano espanso ad alta densità per isolamento superiore in un ingombro contenuto.",
    highlight: "Alta densità in profilo compatto da 41 mm",
    specs: [
      { label: "Materiale", value: "Alluminio preverniciato con PU alta densità" },
      { label: "Profilo", value: "10 × 41 mm" },
      { label: "Peso", value: "~4,0 kg/m²" },
      { label: "Larghezza massima", value: "3.500 mm" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Colori pieni, effetto legno",
    features: ["PU alta densità", "Profilo compatto", "Protezione antigraffio", "Consegna ONEday 24h"],
  },
  "Pasini — Blind 45": {
    name: "Blind 45",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Avvolgibile blindato in alluminio estruso con spessore di 1 mm per la massima resistenza all'effrazione. Struttura senza nervature per un aspetto lineare e moderno. Motorizzazione consigliata dato il peso di 8 kg/m².",
    highlight: "Alluminio estruso 1 mm — massima resistenza antieffrazione",
    specs: [
      { label: "Materiale", value: "Alluminio estruso — spessore 1,0 mm" },
      { label: "Profilo", value: "12 × 45 mm — struttura piatta" },
      { label: "Peso", value: "~8,0 kg/m²" },
      { label: "Larghezza massima", value: "4.000 mm" },
      { label: "Lamelle al m²", value: "22,2" },
      { label: "Movimentazione", value: "Motore tubolare consigliato" },
    ],
    colors: "6 colori pieni standard, 2 effetto legno, RAL personalizzati su richiesta",
    features: ["Alluminio estruso 1 mm", "Struttura piatta senza nervature", "Antieffrazione", "RAL personalizzabili"],
  },
  "Pasini — Blind 27": {
    name: "Blind 27",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Avvolgibile blindato compatto con profilo da 27 mm in alluminio estruso. Progettato per applicazioni di sicurezza in spazi ridotti dove un Blind 45 non è installabile.",
    highlight: "Blindato compatto — sicurezza anche in spazi ridotti",
    specs: [
      { label: "Materiale", value: "Alluminio estruso" },
      { label: "Profilo", value: "27 mm — struttura piatta" },
      { label: "Peso", value: "~6,5 kg/m²" },
      { label: "Movimentazione", value: "Motore tubolare consigliato" },
    ],
    colors: "Colori pieni standard, RAL su richiesta",
    features: ["Alluminio estruso", "Compatto", "Antieffrazione", "Per cassonetti ridotti"],
  },

  /* ── Acciaio ───────────────────────────── */
  "Pasini — Blind 55": {
    name: "Blind 55",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Avvolgibile blindato in acciaio zincato, il più diffuso della gamma in acciaio Pasini. Resistenza meccanica eccezionale contro tentativi di effrazione, per la massima protezione della casa.",
    highlight: "Acciaio zincato — la barriera più resistente contro le effrazioni",
    specs: [
      { label: "Materiale", value: "Acciaio zincato preverniciato" },
      { label: "Profilo", value: "55 mm" },
      { label: "Peso", value: "~10 kg/m²" },
      { label: "Movimentazione", value: "Motore tubolare obbligatorio" },
    ],
    colors: "Colori pieni standard, RAL su richiesta",
    features: ["Acciaio zincato", "Massima antieffrazione", "Struttura rinforzata", "Motorizzazione obbligatoria"],
  },
  "Pasini — Blind 41": {
    name: "Blind 41",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Versione compatta dell'avvolgibile blindato in acciaio con profilo da 41 mm. Sicurezza superiore anche dove gli spazi sono contenuti.",
    highlight: "Acciaio compatto — sicurezza senza compromessi",
    specs: [
      { label: "Materiale", value: "Acciaio zincato" },
      { label: "Profilo", value: "41 mm" },
      { label: "Peso", value: "~8,5 kg/m²" },
      { label: "Movimentazione", value: "Motore tubolare consigliato" },
    ],
    colors: "Colori pieni standard",
    features: ["Acciaio zincato", "Profilo compatto", "Antieffrazione", "Motorizzabile"],
  },

  /* ── PVC ────────────────────────────────── */
  "Pasini — Futura 2.0": {
    name: "Futura 2.0",
    brand: "Pasini",
    segment: "Classic",
    description:
      "Avvolgibile in PVC da 4,8 kg/m², leggero e resistente alla salsedine. Ideale per zone marittime e per chi cerca un prodotto pratico con ottimo rapporto qualità-prezzo.",
    highlight: "PVC leggero e resistente — perfetto per zone marittime",
    specs: [
      { label: "Materiale", value: "PVC ad alta densità" },
      { label: "Peso", value: "~4,8 kg/m²" },
      { label: "Resistenza salsedine", value: "Eccellente" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Bianco, avorio, beige, marrone, grigio, effetto legno",
    features: ["Resistente alla salsedine", "Leggero", "Manutenzione zero", "Consegna ONEday 24h"],
  },
  "Pasini — Futura 4.0": {
    name: "Futura 4.0",
    brand: "Pasini",
    segment: "Premium",
    description:
      "Avvolgibile in PVC ad alta densità da 6,20 kg/m² con formulazione esclusiva anti-deformazione. Resistenza meccanica superiore e mantenimento della forma anche in condizioni climatiche estreme.",
    highlight: "PVC anti-deformazione — resiste al calore senza cedere",
    specs: [
      { label: "Materiale", value: "PVC ad alta densità — formula anti-deformazione" },
      { label: "Peso", value: "~6,20 kg/m²" },
      { label: "Resistenza salsedine", value: "Eccellente" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Bianco, avorio, beige, marrone, grigio, effetto legno",
    features: ["Anti-deformazione", "Alta densità", "Resistente UV", "Zero manutenzione"],
  },
  "Pasini — Futura 4.0 Top": {
    name: "Futura 4.0 Top",
    brand: "Pasini",
    segment: "Top di gamma",
    description:
      "Il top di gamma PVC Pasini: stesso peso e formula del Futura 4.0 con finiture superiori e terminale rinforzato. Per chi non vuole compromessi anche con il PVC.",
    highlight: "Il meglio del PVC — finiture superiori e terminale rinforzato",
    specs: [
      { label: "Materiale", value: "PVC ad alta densità — top di gamma" },
      { label: "Peso", value: "~6,20 kg/m²" },
      { label: "Terminale", value: "Rinforzato con guarnizione" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Gamma completa colori pieni ed effetto legno",
    features: ["Terminale rinforzato", "Anti-deformazione", "Guarnizione di serie", "Top di gamma PVC"],
  },
  "Pasini — Magnum": {
    name: "Magnum",
    brand: "Pasini",
    segment: "Premium",
    description:
      "Avvolgibile in PVC da 6,0 kg/m² con profilo maggiorato per grandi luci. La robustezza del PVC premium per finestre di dimensioni importanti.",
    highlight: "PVC maggiorato per grandi luci — robustezza senza pari",
    specs: [
      { label: "Materiale", value: "PVC ad alta densità" },
      { label: "Peso", value: "~6,0 kg/m²" },
      { label: "Larghezza massima", value: "Grandi luci" },
      { label: "Movimentazione", value: "Cinghia, manovella o motore tubolare" },
    ],
    colors: "Colori pieni standard, effetto legno",
    features: ["Profilo maggiorato", "Per grandi luci", "Alta densità", "Resistente UV"],
  },

  /* ── Screen ────────────────────────────── */
  "Pasini — Vision": {
    name: "Vision",
    brand: "Pasini",
    segment: "Design",
    description:
      "Avvolgibile screen con tessuto microforato che filtra la luce solare mantenendo la visibilità dall'interno verso l'esterno. Protezione UV e riduzione del calore senza rinunciare alla vista panoramica.",
    highlight: "Tessuto microforato — luce filtrata con vista panoramica",
    specs: [
      { label: "Materiale", value: "Tessuto tecnico microforato" },
      { label: "Filtraggio luce", value: "Regolabile in base al tessuto" },
      { label: "Protezione UV", value: "Elevata" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "Gamma tessuti in colori neutri e contemporanei",
    features: ["Vista panoramica mantenuta", "Protezione UV", "Riduzione calore", "Domotica compatibile"],
  },
  "Pasini — Microvision": {
    name: "Microvision",
    brand: "Pasini",
    segment: "Design",
    description:
      "Screen con micro-trama per il massimo filtraggio solare, ideale per facciate vetrate esposte. Rispetto al Vision, offre una maggiore riduzione dell'irraggiamento diretto.",
    highlight: "Micro-trama per massimo filtraggio — ideale per facciate vetrate",
    specs: [
      { label: "Materiale", value: "Tessuto tecnico micro-trama" },
      { label: "Filtraggio solare", value: "Massimo" },
      { label: "Protezione UV", value: "Molto elevata" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "Gamma tessuti colori neutri",
    features: ["Micro-trama", "Massimo filtraggio", "Per facciate vetrate", "Domotica compatibile"],
  },
  "Pasini — Safeblind": {
    name: "Safeblind",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Avvolgibile screen blindato che unisce la protezione antieffrazione alla schermatura solare. Struttura rinforzata con tessuto tecnico resistente per sicurezza e comfort in un'unica soluzione.",
    highlight: "Screen blindato — sicurezza e schermatura solare in un unico prodotto",
    specs: [
      { label: "Materiale", value: "Tessuto tecnico rinforzato" },
      { label: "Sicurezza", value: "Struttura antieffrazione" },
      { label: "Protezione UV", value: "Elevata" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "Gamma tessuti tecnici",
    features: ["Screen blindato", "Antieffrazione", "Protezione solare", "Domotica compatibile"],
  },
  "Pasini — Safeblind Light": {
    name: "Safeblind Light",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Versione alleggerita del Safeblind per applicazioni dove serve protezione senza il peso di un blindato completo. Schermatura solare con sicurezza aggiuntiva.",
    highlight: "Screen con sicurezza leggera — protezione senza peso eccessivo",
    specs: [
      { label: "Materiale", value: "Tessuto tecnico leggero rinforzato" },
      { label: "Sicurezza", value: "Protezione aggiuntiva" },
      { label: "Protezione UV", value: "Elevata" },
      { label: "Movimentazione", value: "Motore tubolare, telecomando, domotica" },
    ],
    colors: "Gamma tessuti tecnici",
    features: ["Screen rinforzato", "Peso contenuto", "Protezione solare", "Domotica compatibile"],
  },

  /* ── Legacy keys (backward compat) ────── */
  "Pasini — Blind 45 AE": {
    name: "Blind 45 AE",
    brand: "Pasini",
    segment: "Sicurezza",
    description:
      "Avvolgibile blindato in alluminio estruso con spessore di 1 mm per la massima resistenza all'effrazione. Struttura senza nervature per un aspetto lineare e moderno. Motorizzazione consigliata dato il peso di 8 kg/m².",
    highlight: "Alluminio estruso 1 mm — massima resistenza antieffrazione",
    specs: [
      { label: "Materiale", value: "Alluminio estruso — spessore 1,0 mm" },
      { label: "Profilo", value: "12 × 45 mm — struttura piatta" },
      { label: "Peso", value: "~8,0 kg/m²" },
      { label: "Larghezza massima", value: "4.000 mm" },
      { label: "Lamelle al m²", value: "22,2" },
      { label: "Movimentazione", value: "Motore tubolare consigliato" },
    ],
    colors: "6 colori pieni standard, 2 effetto legno, RAL personalizzati su richiesta",
    features: ["Alluminio estruso 1 mm", "Struttura piatta senza nervature", "Antieffrazione", "RAL personalizzabili"],
  },
};
