import type { ProductDetail } from "../product-details";

/* ── GRATE DI SICUREZZA — Erreci ─────────────────────────────── */

export const grateDetails: Record<string, ProductDetail> = {
  "Erreci — Sikura (Classe 4)": {
    name: "Sikura",
    brand: "Erreci",
    segment: "Sicurezza Classe 4",
    description:
      "La prima e unica grata di sicurezza con snodo certificata in Classe 4 antieffrazione. Profili in acciaio zincato carbonitrurato con tubolare interno anti-taglio. Ingombro di soli 35 mm, compatibile con monoblocchi senza modifiche agli infissi.",
    highlight: "Unica inferriata con snodo certificata Classe 4 in Italia — solo 35 mm",
    specs: [
      { label: "Materiale", value: "Acciaio zincato carbonitrurato" },
      { label: "Classe antieffrazione", value: "Classe 4 — EN 1627" },
      { label: "Ingombro", value: "Solo 35 mm" },
      { label: "Serratura", value: "Cilindro europeo antitrapano" },
      { label: "Telaio", value: "Sezione 20×30×2 mm, 7 tipologie" },
      { label: "Verniciatura", value: "Polveri poliesteri a forno 180°C" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Snodo brevettato", "Carbonitrurati anti-taglio", "Compatibile monoblocchi", "Profili di compensazione fuori squadra"],
  },
  "Erreci — Libera (Classe 3)": {
    name: "Libera",
    brand: "Erreci",
    segment: "Sicurezza Classe 3",
    description:
      "Inferriata con cerniera a scomparsa brevettata che elimina ogni sporgenza, offrendo un'estetica pulita e un profilo ultra-sottile. Serratura ad infilare a 3 punti con cilindro europeo antitrapano.",
    highlight: "Cerniera a scomparsa brevettata — sicurezza invisibile, design puro",
    specs: [
      { label: "Materiale", value: "Acciaio zincato" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Cerniera", value: "A scomparsa brevettata" },
      { label: "Serratura", value: "Ad infilare, 3 punti, cilindro europeo" },
      { label: "Ante", value: "Profili 40/50×30×2 mm" },
      { label: "Verniciatura", value: "Polveri poliesteri a forno 180°C" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Cerniera a scomparsa", "Design minimale", "Profilo ultra-sottile", "Edifici di pregio"],
  },
  "Erreci — Libera CE (Classe 3)": {
    name: "Libera CE",
    brand: "Erreci",
    segment: "Sicurezza Classe 3",
    description:
      "Grata di sicurezza con cerniere tradizionali ad infilare autolubrificanti e dispositivi becchi antistrappo nei punti di cardine. Costruzione semplificata con rotazione esterna complanare al filo esterno del telaio. Collo disponibile da 12, 30 o 60 mm per adattarsi a ostacoli in facciata.",
    highlight: "Cerniera tradizionale con becchi antistrappo — adattabile a ogni facciata",
    specs: [
      { label: "Materiale", value: "Acciaio zincato" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Telaio", value: "Sezione 40/50×30×2 mm" },
      { label: "Cerniera", value: "Ad infilare autolubrificante con becchi antistrappo" },
      { label: "Serratura", value: "Ad infilare, 3 punti, cilindro europeo antitrapano" },
      { label: "Barre", value: "Tonde piene, 14 mm" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Becchi antistrappo", "Collo regolabile 12/30/60 mm", "Cerniere autolubrificanti", "7 tipologie telaio"],
  },
  "Erreci — Evoluta 18 (Classe 3)": {
    name: "Evoluta 18",
    brand: "Erreci",
    segment: "Sicurezza Classe 3",
    description:
      "Grata di sicurezza con lo speciale snodo brevettato Erreci per apertura fluida e chiusura sicura. Telaio robusto in acciaio zincato sezione 40×30 mm, serratura a 3 punti con cilindro europeo antitrapano.",
    highlight: "Snodo brevettato esclusivo — apertura fluida, telaio 40×30 mm",
    specs: [
      { label: "Materiale", value: "Acciaio zincato" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Telaio", value: "Sezione 40×30×2 mm" },
      { label: "Serratura", value: "3 punti con cilindro europeo antitrapano" },
      { label: "Apertura", value: "A battente con snodo brevettato" },
      { label: "Produzione", value: "Su misura, 100% Made in Italy" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Snodo brevettato", "Telaio robusto 40×30 mm", "Serratura 3 punti", "Su misura"],
  },
  "Erreci — Edilia 2 (Classe 2)": {
    name: "Edilia 2",
    brand: "Erreci",
    segment: "Sicurezza Classe 2",
    description:
      "La grata più sottile della gamma Erreci: soli 35 mm di ingombro, compatibile con monoblocchi senza alcuna modifica agli infissi esistenti. Snodo autobloccante ACS 180 a doppia funzione per apertura interna ed esterna. Struttura semplificata e ultraslim.",
    highlight: "Ultraslim 35 mm — si monta su monoblocchi senza toccare gli infissi",
    specs: [
      { label: "Materiale", value: "Acciaio zincato" },
      { label: "Classe antieffrazione", value: "Classe 2 — EN 1627" },
      { label: "Ingombro", value: "Solo 35 mm" },
      { label: "Telaio", value: "Sezione 30×30×2 mm" },
      { label: "Snodo", value: "ACS 180 autobloccante, doppia funzione" },
      { label: "Serratura", value: "Singola o doppia con chiusini antitalgio" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Ultraslim 35 mm", "Compatibile monoblocchi", "Snodo ACS 180", "7 tipologie telaio"],
  },
  "Erreci — Kiusa (Estensibile)": {
    name: "Kiusa",
    brand: "Erreci",
    segment: "Sicurezza Classe 3",
    description:
      "Grata estensibile a scorrimento per aperture non standard dove non è possibile installare una grata a battente. Barre verticali collegate da leveraggi orizzontali carbonitrurati antitalgio, con carrelli a doppia ruota per uno scorrimento rapido e fluido.",
    highlight: "Estensibile a scorrimento — ideale per aperture non standard",
    specs: [
      { label: "Materiale", value: "Acciaio zincato completamente" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Telaio", value: "Sezione 30×50 mm" },
      { label: "Barre mobili", value: "Sezione 20×40, leveraggi carbonitrurati" },
      { label: "Serratura", value: "2 punti (alto e basso), cilindro europeo antitrapano" },
      { label: "Configurazioni", value: "Singola anta, doppia anta, a cassetta" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere Classe 2",
    features: ["Scorrimento a carrelli", "Leveraggi carbonitrurati", "Configurazione a cassetta", "Aperture non standard"],
  },
  "Erreci — Tenace (Inox AISI 304)": {
    name: "Tenace",
    brand: "Erreci",
    segment: "Acciaio Inox Classe 2",
    description:
      "Grata di sicurezza interamente in acciaio inox AISI 304 con finitura Scotchbrite. Progettata per ambienti marini e costieri con elevata esposizione a salsedine e agenti corrosivi. Snodo autobloccante ACS 180 per apertura interna ed esterna.",
    highlight: "Acciaio inox AISI 304 Scotchbrite — resistenza totale alla salsedine",
    specs: [
      { label: "Materiale", value: "Acciaio inox AISI 304" },
      { label: "Classe antieffrazione", value: "Classe 2 — EN 1627" },
      { label: "Finitura", value: "Scotchbrite" },
      { label: "Telaio", value: "Sezione 30×30×2 mm inox" },
      { label: "Snodo", value: "ACS 180 autobloccante, doppia funzione" },
      { label: "Barre", value: "Tonde piene inox, 14 mm" },
    ],
    colors: "Finitura Scotchbrite naturale",
    features: ["Acciaio inox AISI 304", "Anticorrosione totale", "Finitura Scotchbrite", "Ambienti marini e costieri"],
  },
  "Erreci — Superior (Inox Classe 3)": {
    name: "Superior",
    brand: "Erreci",
    segment: "Acciaio Inox Classe 3",
    description:
      "Il modello premium in acciaio inox della gamma Erreci: certificato Classe 3 con chiusini antitalgio a doppia chiusura. Telaio e ante in AISI 304 finitura Scotchbrite, ideale per ville al mare e contesti che richiedono massima resistenza alla corrosione e sicurezza elevata.",
    highlight: "Inox AISI 304 Classe 3 — il top della sicurezza anticorrosione",
    specs: [
      { label: "Materiale", value: "Acciaio inox AISI 304" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Finitura", value: "Scotchbrite" },
      { label: "Telaio", value: "Sezione 30×30×2 mm inox" },
      { label: "Ante", value: "Profili inox 50/40×30×2 mm" },
      { label: "Serratura", value: "Chiusini antitalgio a doppia chiusura" },
    ],
    colors: "Finitura Scotchbrite naturale",
    features: ["Inox AISI 304 Classe 3", "Chiusini antitalgio", "Anticorrosione premium", "Ville al mare"],
  },
  "Erreci — Marina (Alluminio)": {
    name: "Marina",
    brand: "Erreci",
    segment: "Alluminio Classe 3",
    description:
      "La prima inferriata in alluminio con struttura interna in acciaio blindato: il guscio esterno offre resistenza alla corrosione e leggerezza visiva, il cuore in acciaio garantisce protezione certificata Classe 3. Ingombro di soli 35 mm. Ideale per zone costiere.",
    highlight: "Alluminio fuori, acciaio dentro — anticorrosione, solo 35 mm",
    specs: [
      { label: "Esterno", value: "Alluminio con pretrattamento adesione" },
      { label: "Interno", value: "Struttura portante in acciaio blindato" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Ingombro", value: "Solo 35 mm" },
      { label: "Serratura", value: "2 punti in linea, cilindro europeo con defender" },
      { label: "Verniciatura", value: "Polveri poliesteri a forno 180°C" },
    ],
    colors: "Gamma RAL completa, verniciatura a polvere",
    features: ["Doppio materiale alluminio + acciaio", "Solo 35 mm", "Anticorrosione", "7 moduli ornamentali"],
  },
};

/* ── PERSIANE BLINDATE — Erreci / Ecomet ─────────────────────── */

export const persianeBlinDateDetails: Record<string, ProductDetail> = {
  "Erreci — Maxima Scudo (Classe 3)": {
    name: "Maxima Scudo",
    brand: "Erreci",
    segment: "Sicurezza Classe 3",
    description:
      "Persiana con profili sovradimensionati in acciaio e sistema anti-sfilamento nascosto. Serratura a gancio a 3 punti con escursione catenacci 25 mm. Telaio sagomato a tubo profilato pre-zincato 20/10 con aletta di copertura 20 mm.",
    highlight: "Profili acciaio sovradimensionati — anti-sfilamento nascosto, Classe 3",
    specs: [
      { label: "Struttura", value: "Acciaio pre-zincato 20/10" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Serratura", value: "A gancio, 3 punti, escursione 25 mm" },
      { label: "Telaio", value: "Tubo profilato con aletta 20 mm" },
      { label: "Spessore anta", value: "45 mm" },
      { label: "Verniciatura", value: "Polvere Classe 2, gamma RAL + effetto legno" },
    ],
    colors: "Verde, Marrone, Grigio gotico, RAL 7001/1013/9010/8017/6005/6009, effetto legno",
    features: ["Acciaio sovradimensionato", "Anti-sfilamento nascosto", "Ovaline o stecche", "Verniciatura Classe 2"],
  },
  "Erreci — Combi CE (Classe 3)": {
    name: "Combi CE",
    brand: "Erreci",
    segment: "Premium",
    description:
      "Sistema combinato che abbina la grata di sicurezza Libera CE alla persiana Maxima sullo stesso cardine, con telaio unico di soli 9 cm. Doppia protezione antieffrazione Classe 3 con innumerevoli combinazioni estetiche.",
    highlight: "Grata + persiana sullo stesso cardine — doppia protezione in 9 cm",
    specs: [
      { label: "Componenti", value: "Grata Libera CE + persiana Maxima" },
      { label: "Classe antieffrazione", value: "Classe 3 — EN 1627" },
      { label: "Spessore telaio", value: "Solo 9 cm" },
      { label: "Persiane abbinabili", value: "Classic, Diamante, Skuro, Scandola" },
      { label: "Cerniere", value: "Ad infilare autolubrificanti con rostri antistrappo" },
      { label: "Serratura grata", value: "3 punti con cilindro europeo antitrapano" },
    ],
    colors: "Gamma RAL completa, finiture differenziate grata/persiana",
    features: ["Doppia protezione", "Telaio unico 9 cm", "Cerniere autolubrificanti", "Apertura indipendente"],
  },
  "Erreci — Combi Slim (Classe 2)": {
    name: "Combi Slim",
    brand: "Erreci",
    segment: "Premium",
    description:
      "Versione compatta del sistema combinato Erreci: grata di sicurezza e persiana integrate su un unico telaio di soli 7,5 cm. Struttura in acciaio zincato con cerniere ad infilare e serratura a 2 punti con cilindro europeo. Ideale per finestre di dimensioni contenute.",
    highlight: "Combinato ultra-compatto — grata + persiana in soli 7,5 cm",
    specs: [
      { label: "Componenti", value: "Grata + persiana su telaio unico" },
      { label: "Classe antieffrazione", value: "Classe 2 — EN 1627" },
      { label: "Spessore telaio", value: "Solo 7,5 cm" },
      { label: "Persiane abbinabili", value: "Classic, Diamante, Skuro" },
      { label: "Cerniere", value: "Ad infilare con rostri antistrappo" },
      { label: "Serratura", value: "2 punti con cilindro europeo antitrapano" },
    ],
    colors: "Gamma RAL completa, finiture differenziate grata/persiana",
    features: ["Telaio ultra-compatto 7,5 cm", "Doppia protezione", "Classe 2 certificata", "Finestre di dimensioni contenute"],
  },
  "Ecomet — Persiana ECO (Classe 3)": {
    name: "ECO Persiana",
    brand: "Ecomet",
    segment: "Sicurezza Classe 3",
    description:
      "Persiana blindata in acciaio zincato altoresistenziale assemblata a 90° con serratura a 3 punti e gancio centrale in acciaio temprato. Certificata Classe 3 secondo UNI-ENV 1627. Oltre 28 varianti cromatiche.",
    highlight: "Acciaio altoresistenziale con gancio temprato — Classe 3 certificata",
    specs: [
      { label: "Struttura", value: "Acciaio zincato altoresistenziale, assemblaggio a 90°" },
      { label: "Classe antieffrazione", value: "Classe 3 — UNI-ENV 1627" },
      { label: "Serratura", value: "3 punti: gancio temprato + paletto superiore automatico" },
      { label: "Cilindro", value: "Europeo di sicurezza" },
      { label: "Protezione", value: "Rostri antistrappo, aletta triplice spessore 45/10" },
      { label: "Verniciatura", value: "Polveri poliestere, 24 colori + 4 effetto legno" },
    ],
    colors: "24 colori standard RAL + 4 effetto legno con sublimazione",
    features: ["Gancio temprato", "Paletto automatico", "Rostri antistrappo", "4 finiture legno sublimate"],
  },
  "Ecomet — Grata ECO Apribile": {
    name: "Grata ECO Apribile",
    brand: "Ecomet",
    segment: "Sicurezza Classe 3",
    description:
      "Grata di sicurezza apribile in acciaio zincato altoresistenziale con profili a sezione rettangolare rinforzati. Serratura a 3 punti con cilindro europeo di sicurezza e cerniere ad infilare con rostri antistrappo. Apertura a battente per agevolare la pulizia dei vetri e l'uscita di sicurezza.",
    highlight: "Grata apribile in acciaio altoresistenziale — Classe 3, apertura a battente",
    specs: [
      { label: "Struttura", value: "Acciaio zincato altoresistenziale" },
      { label: "Classe antieffrazione", value: "Classe 3 — UNI-ENV 1627" },
      { label: "Serratura", value: "3 punti con cilindro europeo di sicurezza" },
      { label: "Cerniere", value: "Ad infilare con rostri antistrappo" },
      { label: "Apertura", value: "A battente, 1 o 2 ante" },
      { label: "Verniciatura", value: "Polveri poliestere, 24 colori + 4 effetto legno" },
    ],
    colors: "24 colori standard RAL + 4 effetto legno con sublimazione",
    features: ["Apertura a battente", "Rostri antistrappo", "Uscita di sicurezza", "Pulizia vetri agevole"],
  },
  "Ecomet — ECO Combinato": {
    name: "ECO Combinato",
    brand: "Ecomet",
    segment: "Premium",
    description:
      "Sistema combinato grata + persiana su unico cardine nelle versioni ECOPLUS (persiana acciaio) ed ECOCOMB (persiana legno, alluminio o PVC). Profili in acciaio zincato con elementi tondi, quadri o ad occhiello.",
    highlight: "Grata + persiana su unico cardine — ECOPLUS o ECOCOMB, Classe 3",
    specs: [
      { label: "Versioni", value: "ECOPLUS (acciaio) / ECOCOMB (legno, alluminio, PVC)" },
      { label: "Classe antieffrazione", value: "Classe 3 — UNI-ENV 1627" },
      { label: "Grata", value: "Acciaio zincato con elementi tondi, quadri o occhiello" },
      { label: "Configurazione", value: "1 o 2 ante apribili su cardine unico" },
      { label: "Serratura", value: "3 punti con cilindro europeo" },
      { label: "Produzione", value: "Su misura, Made in Italy" },
    ],
    colors: "24 colori RAL per la grata, persiana personalizzabile",
    features: ["ECOPLUS o ECOCOMB", "Grata e persiana su stesso cardine", "Combinabile con materiali esistenti", "Su misura"],
  },
};

/* ── ALLARME E VIDEOSORVEGLIANZA — Inim ──────────────────────── */

export const allarmeDetails: Record<string, ProductDetail> = {
  "Inim — Sol/G Evo (Wireless)": {
    name: "Sol/G Evo",
    brand: "Inim",
    segment: "Design",
    description:
      "Centrale antifurto completamente wireless all-in-one della serie Sol Evo con tastiera integrata a pulsanti e display grafico. Portata radio fino a 4,5 km con tecnologia Air2 bidirezionale a 868 MHz. Configurazione rapida QuickGO tramite QR-code per fino a 30 dispositivi.",
    highlight: "All-in-one wireless con display grafico — portata 4,5 km, QuickGO",
    specs: [
      { label: "Tecnologia", value: "Wireless all-in-one Air2 bidirezionale 868 MHz" },
      { label: "Portata radio", value: "Fino a 4,5 km" },
      { label: "Certificazione", value: "EN 50131 Grado 2" },
      { label: "Configurazione", value: "QuickGO — 30 dispositivi via QR-code" },
      { label: "Connettività", value: "Wi-Fi, LAN, Cloud Inim" },
      { label: "Interfaccia", value: "Display grafico con tastiera a pulsanti" },
    ],
    colors: "Bianco con frontale elegante",
    features: ["Completamente wireless", "QuickGO QR-code", "Portata 4,5 km", "Display grafico integrato"],
  },
  "Inim — Sol/P (Touch Screen)": {
    name: "Sol/P",
    brand: "Inim",
    segment: "Design",
    description:
      "Centrale antifurto wireless all-in-one con ampio display touch-screen a colori da 7 pollici. Interfaccia intuitiva per gestione completa dell'impianto di sicurezza. Tecnologia Air2 bidirezionale a 868 MHz con portata fino a 4,5 km e configurazione QuickGO.",
    highlight: "Touch-screen 7\" a colori — wireless all-in-one, design premium",
    specs: [
      { label: "Tecnologia", value: "Wireless all-in-one Air2 bidirezionale 868 MHz" },
      { label: "Display", value: "Touch-screen a colori 7 pollici" },
      { label: "Portata radio", value: "Fino a 4,5 km" },
      { label: "Certificazione", value: "EN 50131 Grado 2" },
      { label: "Configurazione", value: "QuickGO — 30 dispositivi via QR-code" },
      { label: "Connettività", value: "Wi-Fi, LAN, Cloud Inim" },
    ],
    colors: "Bianco con display a colori",
    features: ["Touch-screen 7\"", "Completamente wireless", "QuickGO QR-code", "Interfaccia intuitiva"],
  },
  "Inim — SmartLiving 505": {
    name: "SmartLiving 505",
    brand: "Inim",
    segment: "Premium",
    description:
      "Centrale antifurto ibrida filare/wireless Air2 con comunicazione bidirezionale, fino a 5 terminali espandibili a 10. BUS ad alta velocità per gestione rapida dei dispositivi. Compatta e versatile, ideale per abitazioni di medie dimensioni. Certificata EN 50131 Grado 2.",
    highlight: "Centrale ibrida compatta — filare + wireless Air2, Grado 2",
    specs: [
      { label: "Tecnologia", value: "Ibrida: BUS filare + wireless Air2 bidirezionale" },
      { label: "Terminali", value: "5 a bordo, espandibili a 10" },
      { label: "Certificazione", value: "EN 50131-3 Grado 2" },
      { label: "Connettività", value: "LAN, PSTN, GSM con crittografia AES" },
      { label: "Gestione", value: "App Inim + Cloud" },
      { label: "Contenitore", value: "Metallico con tamper antisabotaggio" },
    ],
    colors: "Contenitore metallico bianco; tastiere bianco e nero",
    features: ["Wireless Air2 868 MHz", "BUS alta velocità", "App + Cloud", "Compatta e versatile"],
  },
  "Inim — SmartLiving 1050": {
    name: "SmartLiving 1050",
    brand: "Inim",
    segment: "Premium",
    description:
      "Centrale antifurto ibrida filare/wireless Air2 con comunicazione bidirezionale, fino a 50 terminali espandibili. BUS ad alta velocità, gestione da app e cloud Inim. Certificata EN 50131 Grado 3.",
    highlight: "Centrale ibrida filare + wireless Air2 — Grado 3, app e cloud",
    specs: [
      { label: "Tecnologia", value: "Ibrida: BUS filare + wireless Air2 bidirezionale" },
      { label: "Terminali", value: "Fino a 50 (espandibili)" },
      { label: "Certificazione", value: "EN 50131-3 Grado 3" },
      { label: "Connettività", value: "LAN, PSTN, GSM, GPRS, 3G con AES" },
      { label: "Gestione", value: "App Inim + Cloud + SmartLeague" },
      { label: "Contenitore", value: "Metallico con tamper antisabotaggio" },
    ],
    colors: "Contenitore metallico bianco; tastiere bianco e nero",
    features: ["Wireless Air2 868 MHz", "BUS alta velocità", "App + Cloud", "Domotica integrata"],
  },
  "Inim — InVista Telecamera IP 4MP": {
    name: "InVista Telecamera IP 4MP",
    brand: "Inim",
    segment: "Videosorveglianza",
    description:
      "Telecamera IP bullet da 4 Megapixel della serie InVista con ottica varifocale motorizzata e illuminazione IR fino a 30 metri. Compressione H.265+ per ottimizzare lo spazio di registrazione. Alimentazione PoE integrata per installazione con singolo cavo di rete.",
    highlight: "4 MP con IR 30 m e ottica motorizzata — alimentazione PoE",
    specs: [
      { label: "Risoluzione", value: "4 Megapixel (2560×1440)" },
      { label: "Ottica", value: "Varifocale motorizzata 2,8–12 mm" },
      { label: "IR", value: "Illuminazione fino a 30 m" },
      { label: "Compressione", value: "H.265+ / H.264+" },
      { label: "Alimentazione", value: "PoE (IEEE 802.3af) / 12 VDC" },
      { label: "Protezione", value: "IP67 per installazione esterna" },
    ],
    colors: "Bianco",
    features: ["4 MP ad alta definizione", "IR 30 m", "PoE integrato", "IP67 da esterno"],
  },
  "Inim — InVista NVR 8 canali PoE": {
    name: "InVista NVR 8 canali PoE",
    brand: "Inim",
    segment: "Videosorveglianza",
    description:
      "Network Video Recorder a 8 canali con switch PoE integrato per alimentare direttamente le telecamere IP InVista tramite cavo di rete. Supporta registrazione fino a 4K e riproduzione simultanea su 4 canali. Compatibile con hard disk fino a 6 TB per archiviazione estesa.",
    highlight: "NVR 8 canali con PoE integrato — registrazione 4K, fino a 6 TB",
    specs: [
      { label: "Canali", value: "8 canali IP con switch PoE integrato" },
      { label: "Risoluzione massima", value: "Fino a 4K (8 MP)" },
      { label: "Riproduzione", value: "4 canali simultanei in tempo reale" },
      { label: "Archiviazione", value: "1 SATA fino a 6 TB" },
      { label: "Connettività", value: "HDMI, VGA, LAN Gigabit, USB" },
      { label: "Gestione", value: "App Inim + interfaccia web" },
    ],
    colors: "Nero",
    features: ["PoE integrato 8 porte", "Registrazione 4K", "Archiviazione 6 TB", "App + interfaccia web"],
  },
  "Inim — Prime 060S": {
    name: "Prime 060S",
    brand: "Inim",
    segment: "Premium",
    description:
      "Centrale professionale con scheda di rete integrata. Gestisce fino a 500 sensori e 30 aree, conforme Grado 3 EN 50131 e ATS6 EN 50136. Connettività LAN nativa e servizio Inim Cloud.",
    highlight: "Fino a 500 sensori e 30 aree — scheda di rete integrata, Grado 3",
    specs: [
      { label: "Sensori", value: "Fino a 500 collegabili" },
      { label: "Aree", value: "Fino a 30 gestibili" },
      { label: "Certificazione", value: "EN 50131 Grado 3, EN 50136 ATS6" },
      { label: "Rete", value: "LAN integrata con DHCP, NTP, AES" },
      { label: "Domotica", value: "4 espansioni: avvolgibili, veneziane, luci" },
      { label: "Cloud", value: "Inim Cloud nativo" },
    ],
    colors: "Contenitore metallico professionale",
    features: ["LAN integrata", "500 sensori", "Grado 3 + ATS6", "4 espansioni domotiche"],
  },
  "Inim — Sol": {
    name: "Sol",
    brand: "Inim",
    segment: "Design",
    description:
      "Centrale antifurto completamente wireless, all-in-one, con portata radio fino a 4,5 km. Tecnologia QuickGO per configurazione rapida tramite QR-code. Disponibile nelle versioni Sol/S evo, Sol/G evo e Sol/P con touch-screen.",
    highlight: "All-in-one wireless — portata 4,5 km, configurazione QuickGO con QR-code",
    specs: [
      { label: "Tecnologia", value: "Wireless all-in-one con predisposizione BUS" },
      { label: "Portata radio", value: "Fino a 4,5 km" },
      { label: "Certificazione", value: "EN 50131 Grado 2" },
      { label: "Configurazione", value: "QuickGO — 30 dispositivi via QR-code" },
      { label: "Connettività", value: "Wi-Fi, LAN, Cloud Inim" },
      { label: "Display (Sol/P)", value: "Touch-screen a colori" },
    ],
    colors: "Bianco con frontale elegante; Sol/P con display a colori",
    features: ["Completamente wireless", "QuickGO QR-code", "Portata 4,5 km", "Modulo Wi-Fi"],
  },
  "Inim — Air2 Sensori Wireless": {
    name: "Air2 Sensori Wireless",
    brand: "Inim",
    segment: "Sicurezza",
    description:
      "Gamma di sensori di movimento wireless bidirezionali 868 MHz della serie QTech: volumetrici da interno, a tenda, Pet Immune e da esterno. Comunicazione bidirezionale per verifica deterministica delle segnalazioni.",
    highlight: "Bidirezionali 868 MHz — verifica deterministica, Pet Immune, esterno IP54",
    specs: [
      { label: "Frequenza", value: "868 MHz bidirezionale" },
      { label: "Portata", value: "Fino a 12 m, apertura 90°" },
      { label: "Tecnologie", value: "IR, doppia IR+microonde, Pet Immune (25 kg)" },
      { label: "Certificazione", value: "EN 50131-2-2 Grado 2" },
      { label: "Antisabotaggio", value: "Apertura, rimozione, mascheramento" },
      { label: "Esterno", value: "Copertura 120°, IP54" },
    ],
    colors: "Bianco, design compatto e discreto",
    features: ["Bidirezionale", "Pet Immune 25 kg", "Doppia tecnologia IR+MW", "Antimascheramento"],
  },
};
